function varargout = matlibre_sl_catalogue(action, varargin)
%MATLIBRE_SL_CATALOGUE Le catalogue des blocs : types, paramètres, bibliothèque.
%   CAT = MATLIBRE_SL_CATALOGUE() rend le tableau de structures qui décrit
%   chaque type de bloc que SIM sait simuler : son nom dans MatLibre, son
%   type Simulink (BlockType), son nom dans la bibliothèque de Simulink et
%   ses chemins (« simulink/Math Operations/Gain »), sa famille dans la
%   bibliothèque du bureau, et la liste de ses paramètres avec leur valeur
%   par défaut et leur nature.
%
%   E = MATLIBRE_SL_CATALOGUE('type',DESIGNATION) rend l'entrée d'un type,
%   désigné par son nom MatLibre (« gain »), son type Simulink (« Gain »,
%   « Sin », « Saturate »), son nom de bibliothèque (« Sine Wave »,
%   « Zero-Order Hold ») ou son chemin (« simulink/Sources/Step »). Une
%   désignation inconnue est refusée en disant les types voisins.
%
%   NOM = MATLIBRE_SL_CATALOGUE('parametre',E,NOM) rend l'écriture
%   canonique d'un nom de paramètre pour le type E — la casse est
%   indifférente, comme dans Simulink, et les noms de Simulink et ceux de
%   MatLibre sont reconnus l'un pour l'autre (« Inputs » et « Signs » pour
%   une sommation). Rend '' si le type ne porte pas ce paramètre.
%
%   C'est la source unique de ce que chaque bloc accepte : ADD_BLOCK et
%   SET_PARAM y valident les paramètres, GET_PARAM y lit les valeurs par
%   défaut, SIM y prend les défauts qu'on n'a pas écrits.
%
%   Fonction interne à la boîte à outils : elle n'existe pas dans MATLAB.
%
%   Exemple :
%      e = matlibre_sl_catalogue('type', 'simulink/Math Operations/Gain');
%      e.type                                        % 'gain'
%      matlibre_sl_catalogue('parametre', e, 'gain') % 'Gain'
%
%   Voir aussi ADD_BLOCK, SET_PARAM, GET_PARAM, SIM.
    persistent catalogue index
    if isempty(catalogue)
        catalogue = construire();
        index = indexer(catalogue);
    end
    if nargin == 0
        varargout{1} = catalogue;
        return
    end
    switch lower(char(action))
        case 'type'
            varargout{1} = resoudreType(catalogue, index, varargin{1});
        case 'parametre'
            varargout{1} = resoudreParametre(varargin{1}, varargin{2});
        case 'communs'
            varargout{1} = parametresCommuns();
        otherwise
            error('Simulink:Catalogue:Action', 'Action inconnue : %s.', char(action));
    end
end

% --- les entrées ------------------------------------------------------------
%
% Chaque paramètre est un triplet {nom, défaut, nature}. La nature vaut
% 'nombre' (une valeur ou une expression évaluée dans l'espace de travail
% au moment de simuler), 'texte' (une chaîne lue telle quelle), 'modele'
% (un modèle entier), 'libre' (rangé sans contrôle), ou une liste de choix.
% Un défaut vide pour une période d'échantillonnage veut dire : celle que
% MatLibre prend quand on ne dit rien, et que l'aide du bloc précise.
function cat = construire()
    cat = struct('type', {}, 'simulink', {}, 'affiche', {}, 'famille', {}, ...
                 'description', {}, 'params', {}, 'alias', {}, 'chemins', {}, ...
                 'aliasTypes', {});
    N = 'nombre';
    T = 'texte';

    % --- Sources ---
    cat(end+1) = e('constant', 'Constant', 'Constant', 'Sources', ...
        'Une valeur constante, scalaire, vecteur ou matrice', ...
        {'Value', 1, N; 'SampleTime', Inf, N; ...
         'OutDataTypeStr', 'Inherit: Inherit from ''Constant value''', T}, {}, ...
        {'simulink/Sources/Constant', 'simulink/Commonly Used Blocks/Constant'}, {});
    cat(end+1) = e('enumeratedconstant', 'EnumeratedConstant', 'Enumerated Constant', ...
        'Sources', 'Un membre d''une énumération, constant : un signal de type énuméré', ...
        {'OutDataTypeStr', 'Enum: SlDemoSign', T; 'Value', 'SlDemoSign.Positive', N; ...
         'SampleTime', Inf, N}, {}, {'simulink/Sources/Enumerated Constant'}, {});
    cat(end+1) = e('step', 'Step', 'Step', 'Sources', ...
        'Un échelon à l''instant dit', ...
        {'Time', 1, N; 'Before', 0, N; 'After', 1, N; 'SampleTime', 0, N; ...
         'ZeroCross', 'on', {'on', 'off'}}, ...
        {'InitialValue', 'Before'; 'FinalValue', 'After'}, ...
        {'simulink/Sources/Step'}, {});
    cat(end+1) = e('ramp', 'Ramp', 'Ramp', 'Sources', ...
        'Une rampe de pente donnée, à partir d''un instant', ...
        {'Slope', 1, N; 'Start', 0, N; 'InitialOutput', 0, N}, {'X0', 'InitialOutput'}, ...
        {'simulink/Sources/Ramp'}, {});
    cat(end+1) = e('sine', 'Sin', 'Sine Wave', 'Sources', ...
        'Une sinusoïde', ...
        {'Amplitude', 1, N; 'Frequency', 1, N; 'Phase', 0, N; 'Bias', 0, N; ...
         'SampleTime', 0, N}, {}, ...
        {'simulink/Sources/Sine Wave'}, {'sin', 'sinewave'});
    cat(end+1) = e('clock', 'Clock', 'Clock', 'Sources', ...
        'Le temps de la simulation', ...
        {'DisplayTime', 'off', {'on', 'off'}; 'Decimation', 10, N}, {}, ...
        {'simulink/Sources/Clock'}, {});
    cat(end+1) = e('digitalclock', 'DigitalClock', 'Digital Clock', 'Sources', ...
        'Le temps, tenu entre deux instants d''échantillonnage', ...
        {'SampleTime', 1, N}, {}, {'simulink/Sources/Digital Clock'}, {});
    cat(end+1) = e('pulsegenerator', 'DiscretePulseGenerator', 'Pulse Generator', ...
        'Sources', 'Un train d''impulsions rectangulaires', ...
        {'Amplitude', 1, N; 'Period', 10, N; 'PulseWidth', 5, N; 'PhaseDelay', 0, N; ...
         'PulseType', 'Time based', {'Time based', 'Sample based'}; ...
         'SampleTime', 1, N}, {}, ...
        {'simulink/Sources/Pulse Generator'}, {'pulse'});
    cat(end+1) = e('ground', 'Ground', 'Ground', 'Sources', ...
        'Un zéro, pour une entrée qu''on ne veut pas laisser en l''air', ...
        {}, {}, {'simulink/Sources/Ground', 'simulink/Commonly Used Blocks/Ground'}, {});
    cat(end+1) = e('repeatingsequence', 'RepeatingSequence', 'Repeating Sequence', ...
        'Sources', 'Une séquence périodique, interpolée entre ses points', ...
        {'rep_seq_t', [0 2], N; 'rep_seq_y', [0 2], N}, ...
        {'TimeValues', 'rep_seq_t'; 'OutputValues', 'rep_seq_y'}, ...
        {'simulink/Sources/Repeating Sequence'}, {});
    cat(end+1) = e('randomnumber', 'RandomNumber', 'Random Number', 'Sources', ...
        'Un bruit gaussien, reproductible par sa graine', ...
        {'Mean', 0, N; 'Variance', 1, N; 'Seed', 0, N; 'SampleTime', 0.1, N}, {}, ...
        {'simulink/Sources/Random Number'}, {});
    cat(end+1) = e('uniformrandomnumber', 'UniformRandomNumber', ...
        'Uniform Random Number', 'Sources', ...
        'Un bruit uniforme, reproductible par sa graine', ...
        {'Minimum', -1, N; 'Maximum', 1, N; 'Seed', 0, N; 'SampleTime', 0.1, N}, {}, ...
        {'simulink/Sources/Uniform Random Number'}, {});
    cat(end+1) = e('chirp', 'Chirp', 'Chirp Signal', 'Sources', ...
        'Une sinusoïde dont la fréquence croît linéairement, de f1 à f2 en T', ...
        {'f1', 0.1, N; 'T', 100, N; 'f2', 1, N}, ...
        {'InitialFrequency', 'f1'; 'TargetTime', 'T'; 'FrequencyAtTargetTime', 'f2'}, ...
        {'simulink/Sources/Chirp Signal'}, {'chirpsignal'});
    cat(end+1) = e('bandlimitedwhitenoise', 'BandLimitedWhiteNoise', ...
        'Band-Limited White Noise', 'Sources', ...
        'Un bruit blanc de puissance donnée, tenu à chaque période', ...
        {'Cov', 0.1, N; 'Ts', 0.1, N; 'seed', 23341, N}, ...
        {'NoisePower', 'Cov'; 'SampleTime', 'Ts'; 'Seed', 'seed'}, ...
        {'simulink/Sources/Band-Limited White Noise'}, {'band-limitedwhitenoise'});
    cat(end+1) = e('counterfreerunning', 'CounterFreeRunning', 'Counter Free-Running', ...
        'Sources', 'Compte les instants, et repart de zéro après 2^NumBits - 1', ...
        {'NumBits', 16, N; 'tsamp', -1, N}, {'SampleTime', 'tsamp'}, ...
        {'simulink/Sources/Counter Free-Running'}, {'counterfree-running'});
    cat(end+1) = e('counterlimited', 'CounterLimited', 'Counter Limited', 'Sources', ...
        'Compte les instants jusqu''à sa limite, puis repart de zéro', ...
        {'uplimit', 7, N; 'tsamp', -1, N}, {'UpperLimit', 'uplimit'; 'SampleTime', 'tsamp'}, ...
        {'simulink/Sources/Counter Limited'}, {});
    cat(end+1) = e('signalgenerator', 'SignalGenerator', 'Signal Generator', 'Sources', ...
        'Sinus, carré, dent de scie ou bruit, d''amplitude et de fréquence données', ...
        {'WaveForm', 'sine', {'sine', 'square', 'sawtooth', 'random'}; ...
         'Amplitude', 1, N; 'Frequency', 1, N; 'Units', 'rad/sec', {'rad/sec', 'Hertz'}}, ...
        {}, {'simulink/Sources/Signal Generator'}, {});
    cat(end+1) = e('repeatingsequencestair', 'RepeatingSequenceStair', ...
        'Repeating Sequence Stair', 'Sources', ...
        'Une suite de valeurs, rendues tour à tour à chaque instant, sans fin', ...
        {'OutValues', [3 1 4 2 1], N; 'tsamp', -1, N}, {'SampleTime', 'tsamp'}, ...
        {'simulink/Sources/Repeating Sequence Stair'}, {});
    cat(end+1) = e('inport', 'Inport', 'In1', 'Sources', ...
        'L''entrée du modèle, vue par LINMOD', ...
        {'Port', 1, N; 'Value', 0, N; 'PortDimensions', -1, N; ...
         'OutDataTypeStr', 'Inherit: auto', T}, {}, ...
        {'simulink/Sources/In1', 'simulink/Ports & Subsystems/In1', ...
         'simulink/Commonly Used Blocks/In1'}, {'in1', 'in'});
    cat(end+1) = e('fromfile', 'FromFile', 'From File', 'Sources', ...
        'Un signal lu dans un fichier MAT : le temps sur la première ligne', ...
        {'FileName', 'untitled.mat', T; 'SampleTime', 0, N; ...
         'ExtrapolationBeforeFirstDataPoint', 'Linear extrapolation', ...
         {'Linear extrapolation', 'Hold first value', 'Ground value'}; ...
         'InterpolationWithinTimeRange', 'Linear interpolation', ...
         {'Linear interpolation', 'Zero-order hold'}; ...
         'ExtrapolationAfterLastDataPoint', 'Linear extrapolation', ...
         {'Linear extrapolation', 'Hold last value', 'Ground value'}}, {'Filename', 'FileName'}, ...
        {'simulink/Sources/From File'}, {});
    cat(end+1) = e('repeatingsequenceinterpolated', 'RepeatingSequenceInterpolated', ...
        'Repeating Sequence Interpolated', 'Sources', ...
        'Une séquence périodique de valeurs datées, lue dans une table', ...
        {'OutValues', [3; 1; 4; 2; 1], N; 'TimeValues', [0; 0.1; 0.5; 0.6; 1], N; ...
         'LookUpMeth', 'Interpolation-Use End Values', {'Interpolation-Extrapolation', 'Interpolation-Use End Values', 'Use Input Nearest', 'Use Input Below', 'Use Input Above'}; ...
         'tsamp', 0.01, N}, {'SampleTime', 'tsamp'}, ...
        {'simulink/Sources/Repeating Sequence Interpolated'}, {});
    cat(end+1) = e('signaleditor', 'SignalEditor', 'Signal Editor', 'Sources', ...
        'Rejoue les signaux d''un scénario : un Dataset rangé dans un fichier MAT', ...
        {'FileName', 'untitled.mat', T; 'ActiveScenario', 'Scenario', T; ...
         'SampleTime', 0, N}, {}, {'simulink/Sources/Signal Editor'}, {});
    cat(end+1) = e('fromspreadsheet', 'FromSpreadsheet', 'From Spreadsheet', 'Sources', ...
        'Lit un signal dans un tableur : la première colonne, les instants', ...
        {'FileName', 'untitled.csv', T; 'Range', '', T; ...
         'InterpolationWithinTimeRange', 'Linear interpolation', ...
         {'Linear interpolation', 'Zero order hold'}; ...
         'ExtrapolationAfterLastDataPoint', 'Linear extrapolation', ...
         {'Linear extrapolation', 'Hold last value', 'Ground value'}; ...
         'SampleTime', 0, N}, {}, {'simulink/Sources/From Spreadsheet'}, {});
    cat(end+1) = e('fromworkspace', 'FromWorkspace', 'From Workspace', 'Sources', ...
        'Un signal lu dans l''espace de travail', ...
        {'VariableName', '', T; 'Interpolate', 'on', {'on', 'off'}; ...
         'OutputAfterFinalValue', 'Holding final value', ...
         {'Extrapolation', 'Setting to zero', 'Holding final value'}; ...
         'SampleTime', 0, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Sources/From Workspace'}, {});

    % --- Opérations ---
    cat(end+1) = e('gain', 'Gain', 'Gain', 'Opérations', ...
        'Multiplie par un gain, terme à terme ou matriciel', ...
        {'Gain', 1, N; 'Multiplication', 'Element-wise(K.*u)', ...
         {'Element-wise(K.*u)', 'Matrix(K*u)', 'Matrix(u*K)', 'Matrix(K*u) (u vector)'}; ...
         'SampleTime', -1, N; 'RndMeth', 'Floor', {'Zero', 'Nearest', 'Round', 'Floor', 'Ceiling', 'Convergent', 'Simplest'}; ...
         'SaturateOnIntegerOverflow', 'off', {'off', 'on'}; ...
         'OutDataTypeStr', 'Inherit: Inherit via internal rule', T; ...
         'ParamDataTypeStr', 'Inherit: Inherit via internal rule', T}, {}, ...
        {'simulink/Math Operations/Gain', 'simulink/Commonly Used Blocks/Gain'}, ...
        {'slidergain'});
    cat(end+1) = e('sum', 'Sum', 'Sum', 'Opérations', ...
        'Somme ses entrées selon leurs signes ; une seule entrée : somme de ses éléments', ...
        {'Signs', '++', T; 'IconShape', 'rectangular', 'libre'; 'SampleTime', -1, N; ...
         'RndMeth', 'Floor', {'Zero', 'Nearest', 'Round', 'Floor', 'Ceiling', 'Convergent', 'Simplest'}; ...
         'SaturateOnIntegerOverflow', 'off', {'off', 'on'}; ...
         'OutDataTypeStr', 'Inherit: Inherit via internal rule', T}, ...
        {'Inputs', 'Signs'; 'ListOfSigns', 'Signs'}, ...
        {'simulink/Math Operations/Sum', 'simulink/Math Operations/Add', ...
         'simulink/Math Operations/Subtract', 'simulink/Math Operations/Sum of Elements', ...
         'simulink/Commonly Used Blocks/Sum'}, {'add', 'subtract', 'sumofelements'});
    cat(end+1) = e('product', 'Product', 'Product', 'Opérations', ...
        'Multiplie ou divise ses entrées ; une seule entrée : produit de ses éléments', ...
        {'Inputs', '**', T; 'Multiplication', 'Element-wise(.*)', ...
         {'Element-wise(.*)', 'Matrix(*)'}; 'SampleTime', -1, N; ...
         'RndMeth', 'Zero', {'Zero', 'Nearest', 'Round', 'Floor', 'Ceiling', 'Convergent', 'Simplest'}; ...
         'SaturateOnIntegerOverflow', 'off', {'off', 'on'}; ...
         'OutDataTypeStr', 'Inherit: Inherit via internal rule', T}, {}, ...
        {'simulink/Math Operations/Product', 'simulink/Math Operations/Divide', ...
         'simulink/Math Operations/Product of Elements', ...
         'simulink/Commonly Used Blocks/Product'}, {'divide', 'productofelements'});
    cat(end+1) = e('abs', 'Abs', 'Abs', 'Opérations', 'Valeur absolue', ...
        {'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Math Operations/Abs'}, {});
    cat(end+1) = e('complextorealimag', 'ComplexToRealImag', 'Complex to Real-Imag', ...
        'Opérations', 'Les parties réelle et imaginaire d''un signal complexe', ...
        {'Output', 'Real and imag', {'Real and imag', 'Real', 'Imag'}; ...
         'SampleTime', -1, N}, {}, {'simulink/Math Operations/Complex to Real-Imag'}, {});
    cat(end+1) = e('realimagtocomplex', 'RealImagToComplex', 'Real-Imag to Complex', ...
        'Opérations', 'Un signal complexe, de ses parties réelle et imaginaire', ...
        {'Input', 'Real and imag', {'Real and imag', 'Real', 'Imag'}; ...
         'ConstantPart', 0, N; 'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Real-Imag to Complex'}, {});
    cat(end+1) = e('complextomagnitudeangle', 'ComplexToMagnitudeAngle', ...
        'Complex to Magnitude-Angle', 'Opérations', ...
        'Le module et l''argument d''un signal complexe', ...
        {'Output', 'Magnitude and angle', {'Magnitude and angle', 'Magnitude', 'Angle'}; ...
         'SampleTime', -1, N}, {}, {'simulink/Math Operations/Complex to Magnitude-Angle'}, {});
    cat(end+1) = e('magnitudeangletocomplex', 'MagnitudeAngleToComplex', ...
        'Magnitude-Angle to Complex', 'Opérations', ...
        'Un signal complexe, de son module et de son argument', ...
        {'Input', 'Magnitude and angle', {'Magnitude and angle', 'Magnitude', 'Angle'}; ...
         'ConstantPart', 0, N; 'ApproximationMethod', 'None', {'None', 'CORDIC'}; ...
         'NumberOfIterations', 11, N; 'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Magnitude-Angle to Complex'}, {});
    cat(end+1) = e('sign', 'Signum', 'Sign', 'Opérations', 'Le signe : -1, 0 ou 1', ...
        {'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Math Operations/Sign'}, {'signum'});
    cat(end+1) = e('math', 'Math', 'Math Function', 'Opérations', ...
        'Carré, racine, exponentielle, logarithme, puissance, modulo...', ...
        {'Operator', 'square', {'exp', 'log', '10^u', 'log10', 'magnitude^2', ...
         'square', 'sqrt', 'pow', 'conj', 'reciprocal', 'hypot', 'rem', 'mod', ...
         'transpose', 'hermitian'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Math Function'}, {'mathfunction'});
    cat(end+1) = e('trigonometry', 'Trigonometry', 'Trigonometric Function', ...
        'Opérations', 'Sinus, cosinus, tangente, leurs réciproques et hyperboliques', ...
        {'Operator', 'sin', {'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2', ...
         'sinh', 'cosh', 'tanh', 'asinh', 'acosh', 'atanh', 'sincos', 'cos + jsin'}; ...
         'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Trigonometric Function'}, ...
        {'trigonometricfunction'});
    cat(end+1) = e('minmax', 'MinMax', 'MinMax', 'Opérations', ...
        'Le plus petit ou le plus grand ; une seule entrée : sur ses éléments', ...
        {'Function', 'min', {'min', 'max'}; 'Inputs', 2, N; 'SampleTime', -1, N; ...
         'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Math Operations/MinMax'}, {});
    cat(end+1) = e('datatypeconversion', 'DataTypeConversion', 'Data Type Conversion', ...
        'Opérations', ['Convertit le signal dans un type : entier, simple précision, ' ...
                       'booléen, virgule fixe'], ...
        {'OutDataTypeStr', 'Inherit: Inherit via back propagation', T; ...
         'ConvertRealWorld', 'Real World Value (RWV)', ...
         {'Real World Value (RWV)', 'Stored Integer (SI)'}; ...
         'RndMeth', 'Zero', {'Zero', 'Nearest', 'Round', 'Floor', 'Ceiling', 'Convergent', ...
                             'Simplest'}; ...
         'SaturateOnIntegerOverflow', 'off', {'off', 'on'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Signal Attributes/Data Type Conversion', ...
         'simulink/Commonly Used Blocks/Data Type Conversion'}, {});
    cat(end+1) = e('bias', 'Bias', 'Bias', 'Opérations', 'Ajoute une constante', ...
        {'Bias', 0, N; 'SampleTime', -1, N}, {}, {'simulink/Math Operations/Bias'}, {});
    cat(end+1) = e('dotproduct', 'DotProduct', 'Dot Product', 'Opérations', ...
        'Le produit scalaire de ses deux entrées', ...
        {'SampleTime', -1, N}, {}, {'simulink/Math Operations/Dot Product'}, {});
    cat(end+1) = e('unaryminus', 'UnaryMinus', 'Unary Minus', 'Opérations', ...
        'L''opposé', {'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Unary Minus'}, {});
    cat(end+1) = e('rounding', 'Rounding', 'Rounding Function', 'Opérations', ...
        'Arrondit : floor, ceil, round ou fix', ...
        {'Operator', 'floor', {'floor', 'ceil', 'round', 'fix'}; 'SampleTime', -1, N}, ...
        {}, {'simulink/Math Operations/Rounding Function'}, {'roundingfunction'});
    cat(end+1) = e('polynomial', 'Polyval', 'Polynomial', 'Opérations', ...
        'Évalue un polynôme en son entrée', ...
        {'coefs', [1 0], N; 'SampleTime', -1, N}, {'Coefs', 'coefs'}, ...
        {'simulink/Math Operations/Polynomial'}, {'polyval'});
    cat(end+1) = e('sqrt', 'Sqrt', 'Sqrt', 'Opérations', ...
        'Racine carrée ; son inverse ; ou racine du module avec le signe', ...
        {'Operator', 'sqrt', {'sqrt', 'signedSqrt', 'rSqrt'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Sqrt', 'simulink/Math Operations/Signed Sqrt', ...
         'simulink/Math Operations/Reciprocal Sqrt'}, {'signedsqrt', 'reciprocalsqrt'});
    cat(end+1) = e('sinewavefunction', 'SineWaveFunction', 'Sine Wave Function', ...
        'Opérations', 'A sin(F u + P) + B : une sinusoïde de l''entrée, qui tient lieu de temps', ...
        {'SineType', 'Time based', {'Time based', 'Sample based'}; 'Amplitude', 1, N; ...
         'Bias', 0, N; 'Frequency', 1, N; 'Phase', 0, N; 'Samples', 10, N; 'Offset', 0, N; ...
         'SampleTime', -1, N}, {}, {'simulink/Math Operations/Sine Wave Function'}, {});
    cat(end+1) = e('algebraicconstraint', 'AlgebraicConstraint', 'Algebraic Constraint', ...
        'Opérations', 'Rend z tel que son entrée f(z) s''annule, ou vaille z', ...
        {'Constraint', 'f(z) = 0', {'f(z) = 0', 'f(z) = z'}; 'InitialGuess', 0, N}, ...
        {}, {'simulink/Math Operations/Algebraic Constraint'}, {});
    cat(end+1) = e('sampletimemath', 'SampleTimeMath', 'Weighted Sample Time Math', ...
        'Opérations', 'Ajoute, retranche, multiplie ou divise l''entrée par w Ts', ...
        {'TsampMathOp', '+', {'+', '-', '*', '/', 'Ts Only', '1/Ts Only'}; ...
         'weightValue', 1, N}, {'WeightValue', 'weightValue'}, ...
        {'simulink/Math Operations/Weighted Sample Time Math'}, ...
        {'weightedsampletimemath'});
    cat(end+1) = e('minmaxrunningresettable', 'MinMaxRunningResettable', ...
        'MinMax Running Resettable', 'Opérations', ...
        'Le plus petit ou le plus grand des u passés ; R le remet à sa valeur initiale', ...
        {'Function', 'min', {'min', 'max'}; 'vinit', 0, N}, ...
        {'InitialCondition', 'vinit'}, ...
        {'simulink/Math Operations/MinMax Running Resettable'}, {});
    cat(end+1) = e('permutedimensions', 'PermuteDimensions', 'Permute Dimensions', ...
        'Opérations', 'Réordonne les dimensions de l''entrée, comme PERMUTE', ...
        {'Order', [2 1], N}, {}, {'simulink/Math Operations/Permute Dimensions'}, {});
    cat(end+1) = e('squeeze', 'Squeeze', 'Squeeze', 'Opérations', ...
        'Ôte les dimensions de taille 1, comme SQUEEZE', {}, {}, ...
        {'simulink/Math Operations/Squeeze'}, {});

    % --- Non-linéarités ---
    cat(end+1) = e('saturation', 'Saturate', 'Saturation', 'Non-linéarités', ...
        'Borne le signal', ...
        {'UpperLimit', 1, N; 'LowerLimit', -1, N; 'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Discontinuities/Saturation', ...
         'simulink/Commonly Used Blocks/Saturation'}, {'saturate'});
    cat(end+1) = e('deadzone', 'DeadZone', 'Dead Zone', 'Non-linéarités', ...
        'Annule une bande autour de zéro', ...
        {'UpperValue', 0.5, N; 'LowerValue', -0.5, N; 'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, ...
        {'Start', 'LowerValue'; 'End', 'UpperValue'}, ...
        {'simulink/Discontinuities/Dead Zone'}, {});
    cat(end+1) = e('relay', 'Relay', 'Relay', 'Non-linéarités', ...
        'Bascule à deux seuils', ...
        {'OnSwitch', 0.5, N; 'OffSwitch', -0.5, N; 'OnOutput', 1, N; ...
         'OffOutput', 0, N; 'ZeroCross', 'on', {'on', 'off'}}, ...
        {'OnSwitchValue', 'OnSwitch'; 'OffSwitchValue', 'OffSwitch'; ...
         'OnOutputValue', 'OnOutput'; 'OffOutputValue', 'OffOutput'}, ...
        {'simulink/Discontinuities/Relay'}, {});
    cat(end+1) = e('quantizer', 'Quantizer', 'Quantizer', 'Non-linéarités', ...
        'Arrondit à un pas donné', ...
        {'QuantizationInterval', 0.5, N; 'SampleTime', -1, N}, {}, ...
        {'simulink/Discontinuities/Quantizer'}, {});
    cat(end+1) = e('ratelimiter', 'RateLimiter', 'Rate Limiter', 'Non-linéarités', ...
        'Borne la pente du signal', ...
        {'RisingSlewLimit', 1, N; 'FallingSlewLimit', -1, N; 'InitialOutput', 0, N}, ...
        {'RisingSlewRate', 'RisingSlewLimit'; 'FallingSlewRate', 'FallingSlewLimit'}, ...
        {'simulink/Discontinuities/Rate Limiter'}, {});
    cat(end+1) = e('hitcrossing', 'HitCross', 'Hit Crossing', 'Non-linéarités', ...
        'Vaut 1 à l''instant où l''entrée franchit un seuil', ...
        {'HitCrossingOffset', 0, N; 'HitCrossingDirection', 'either', ...
         {'rising', 'falling', 'either'}; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Discontinuities/Hit Crossing'}, {'hitcross'});
    cat(end+1) = e('backlash', 'Backlash', 'Backlash', 'Non-linéarités', ...
        'Un jeu mécanique : la sortie ne suit qu''au-delà d''une largeur', ...
        {'BacklashWidth', 1, N; 'InitialOutput', 0, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Discontinuities/Backlash'}, {});
    cat(end+1) = e('coulombfriction', 'CoulombViscousFriction', ...
        'Coulomb & Viscous Friction', 'Non-linéarités', ...
        'Frottement sec et visqueux : signe(u) (offset + gain |u|)', ...
        {'offset', 1, N; 'gain', 1, N; 'ZeroCross', 'on', {'on', 'off'}}, {'Offset', 'offset'; 'Gain', 'gain'}, ...
        {'simulink/Discontinuities/Coulomb & Viscous Friction'}, ...
        {'coulombviscousfriction'});
    cat(end+1) = e('wraptozero', 'WrapToZero', 'Wrap To Zero', 'Non-linéarités', ...
        'L''entrée, ou zéro quand elle dépasse le seuil', ...
        {'Threshold', 255, N}, {}, {'simulink/Discontinuities/Wrap To Zero'}, {});
    cat(end+1) = e('saturationdynamic', 'SaturationDynamic', 'Saturation Dynamic', ...
        'Non-linéarités', 'Borne l''entrée u entre les signaux lo et up', ...
        {}, {}, {'simulink/Discontinuities/Saturation Dynamic'}, {});
    cat(end+1) = e('ratelimiterdynamic', 'RateLimiterDynamic', 'Rate Limiter Dynamic', ...
        'Non-linéarités', 'Borne la pente de u entre les signaux lo et up', ...
        {}, {}, {'simulink/Discontinuities/Rate Limiter Dynamic'}, {});
    cat(end+1) = e('deadzonedynamic', 'DeadZoneDynamic', 'Dead Zone Dynamic', ...
        'Non-linéarités', 'Annule l''entrée u entre les signaux lo et up', ...
        {}, {}, {'simulink/Discontinuities/Dead Zone Dynamic'}, {});
    cat(end+1) = e('lookup', 'Lookup_n-D', '1-D Lookup Table', 'Non-linéarités', ...
        'Interpole dans une table ; hors des bornes, tenue ou prolongée', ...
        {'BreakpointsData', [0 1], N; 'TableData', [0 1], N; ...
         'InterpMethod', 'Linear point-slope', {'Linear point-slope', 'Linear', ...
         'Flat', 'Nearest'}; 'ExtrapMethod', 'Clip', {'Clip', 'Linear'}; ...
         'SampleTime', -1, N; 'NumberOfTableDimensions', 1, N; ...
         'BreakpointsForDimension2', [0 1], N; 'BreakpointsForDimension3', [0 1], N; ...
         'BreakpointsForDimension4', [0 1], N; 'BreakpointsForDimension5', [0 1], N; ...
         'BreakpointsForDimension6', [0 1], N}, ...
        {'BreakpointsForDimension1', 'BreakpointsData'; 'Table', 'TableData'}, ...
        {'simulink/Lookup Tables/1-D Lookup Table', ...
         'simulink/Lookup Tables/n-D Lookup Table'}, ...
        {'lookup_n-d', 'lookuptable', '1-dlookuptable', 'n-dlookuptable'});
    cat(end+1) = e('lookuptabledynamic', 'LookupTableDynamic', 'Lookup Table Dynamic', ...
        'Non-linéarités', 'Interpole x dans la table que ses entrées xdat et ydat apportent', ...
        {'LookUpMeth', 'Interpolation-Use End Values', {'Interpolation-Extrapolation', ...
         'Interpolation-Use End Values', 'Use Input Nearest', 'Use Input Below', ...
         'Use Input Above'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Lookup Tables/Lookup Table Dynamic'}, {});
    cat(end+1) = e('prelookup', 'PreLookup', 'Prelookup', 'Non-linéarités', ...
        'L''indice k, à partir de 0, et la fraction f de l''entrée parmi les points de rupture', ...
        {'BreakpointsData', 10:10:110, N; 'OutputSelection', 'Index and fraction', ...
         {'Index and fraction', 'Index only'}; 'ExtrapMethod', 'Clip', {'Clip', 'Linear'}; ...
         'UseLastBreakpoint', 'off', {'on', 'off'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Lookup Tables/Prelookup'}, {});
    cat(end+1) = e('interpolationusingprelookup', 'Interpolation_n-D', ...
        'Interpolation Using Prelookup', 'Non-linéarités', ...
        'Interpole une table aux indices et fractions que donnent des Prelookup', ...
        {'NumberOfTableDimensions', 2, N; 'Table', sqrt((1:11)' * (1:11)), N; ...
         'InterpMethod', 'Linear point-slope', {'Linear point-slope', 'Linear', 'Flat', ...
         'Nearest'}; 'ExtrapMethod', 'Clip', {'Clip', 'Linear'}; ...
         'ValidIndexMayReachLast', 'off', {'on', 'off'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Lookup Tables/Interpolation Using Prelookup'}, {'interpolation_n-d'});
    cat(end+1) = e('sinecosine', 'SineCosine', 'Sine, Cosine', 'Non-linéarités', ...
        'sin(2 pi u), cos(2 pi u), ou les deux, lus dans une table d''un quart d''onde', ...
        {'Formula', 'sin(2*pi*u)', {'sin(2*pi*u)', 'cos(2*pi*u)', ...
         'sin(2*pi*u) and cos(2*pi*u)'}; 'NumDataPoints', 2^5 + 1, N}, {}, ...
        {'simulink/Lookup Tables/Sine, Cosine'}, {'sineandcosine'});
    cat(end+1) = e('directlookup', 'LookupNDDirect', 'Direct Lookup Table (n-D)', ...
        'Non-linéarités', 'Rend l''élément de la table que ses entrées désignent, à partir de 0', ...
        {'Table', [4 5 6 7], N; 'NumberOfTableDimensions', 1, N; 'SampleTime', -1, N}, ...
        {'maskTabDims', 'NumberOfTableDimensions'}, ...
        {'simulink/Lookup Tables/Direct Lookup Table (n-D)'}, ...
        {'directlookuptable(n-d)', 'directlookuptable'});
    cat(end+1) = e('lookup2d', 'Lookup2D', '2-D Lookup Table', 'Non-linéarités', ...
        'Interpole dans une table à deux entrées', ...
        {'BreakpointsForDimension1', [0 1], N; 'BreakpointsForDimension2', [0 1], N; ...
         'Table', [0 0; 0 1], N; 'SampleTime', -1, N}, ...
        {'RowIndex', 'BreakpointsForDimension1'; ...
         'ColumnIndex', 'BreakpointsForDimension2'; 'OutputValues', 'Table'}, ...
        {'simulink/Lookup Tables/2-D Lookup Table'}, {'2-dlookuptable'});

    % --- Logique ---
    cat(end+1) = e('combinatoriallogic', 'CombinatorialLogic', 'Combinatorial Logic', ...
        'Logique', 'La ligne de la table de vérité que désignent ses entrées booléennes', ...
        {'TruthTable', [0 0; 0 1; 0 1; 1 0], N; 'SampleTime', -1, N}, {}, ...
        {'simulink/Logic and Bit Operations/Combinatorial Logic'}, {});
    cat(end+1) = e('logic', 'Logic', 'Logical Operator', 'Logique', ...
        'ET, OU, NON, OU exclusif ; une seule entrée : sur ses éléments', ...
        {'Operator', 'AND', {'AND', 'OR', 'NAND', 'NOR', 'XOR', 'NXOR', 'NOT'}; ...
         'Inputs', 2, N; 'SampleTime', -1, N; ...
         'OutDataTypeStr', 'boolean', {'boolean', 'double', 'single', 'int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32'}}, {}, ...
        {'simulink/Logic and Bit Operations/Logical Operator', ...
         'simulink/Commonly Used Blocks/Logical Operator'}, {'logicaloperator'});
    cat(end+1) = e('relational', 'RelationalOperator', 'Relational Operator', ...
        'Logique', 'Compare deux entrées', ...
        {'Operator', '<', {'==', '~=', '<', '<=', '>=', '>'}; 'SampleTime', -1, N; ...
         'ZeroCross', 'on', {'on', 'off'}; 'OutDataTypeStr', 'boolean', {'boolean', 'double', 'single', 'int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32'}}, {}, ...
        {'simulink/Logic and Bit Operations/Relational Operator', ...
         'simulink/Commonly Used Blocks/Relational Operator'}, ...
        {'relationaloperator'});
    cat(end+1) = e('comparetoconstant', 'CompareToConstant', 'Compare To Constant', ...
        'Logique', 'Compare l''entrée à une constante', ...
        {'relop', '<=', {'==', '~=', '<', '<=', '>=', '>'}; 'const', 3, N; 'ZeroCross', 'on', ...
         {'on', 'off'}; 'OutDataTypeStr', 'boolean', {'boolean', 'double', 'single', 'int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32'}}, ...
        {'Operator', 'relop'; 'Constant', 'const'}, ...
        {'simulink/Logic and Bit Operations/Compare To Constant'}, {});
    cat(end+1) = e('comparetozero', 'CompareToZero', 'Compare To Zero', 'Logique', ...
        'Compare l''entrée à zéro', ...
        {'relop', '<=', {'==', '~=', '<', '<=', '>=', '>'}; 'ZeroCross', 'on', {'on', 'off'}; ...
         'OutDataTypeStr', 'boolean', {'boolean', 'double', 'single', 'int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32'}}, ...
        {'Operator', 'relop'}, ...
        {'simulink/Logic and Bit Operations/Compare To Zero'}, {});
    cat(end+1) = e('detectchange', 'DetectChange', 'Detect Change', 'Logique', ...
        'Vaut 1 quand l''entrée diffère de celle du pas précédent', ...
        {'vinit', 0, N; 'OutDataTypeStr', 'boolean', {'boolean', 'double', 'single', 'int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32'}}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Change'}, {});
    cat(end+1) = e('detectincrease', 'DetectIncrease', 'Detect Increase', 'Logique', ...
        'Vaut 1 quand l''entrée a augmenté depuis le pas précédent', ...
        {'vinit', 0, N; 'OutDataTypeStr', 'boolean', {'boolean', 'double', 'single', 'int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32'}}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Increase'}, {});
    cat(end+1) = e('detectdecrease', 'DetectDecrease', 'Detect Decrease', 'Logique', ...
        'Vaut 1 quand l''entrée a diminué depuis le pas précédent', ...
        {'vinit', 0, N; 'OutDataTypeStr', 'boolean', {'boolean', 'double', 'single', 'int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32'}}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Decrease'}, {});
    cat(end+1) = e('detectrisepositive', 'DetectRisePositive', 'Detect Rise Positive', ...
        'Logique', 'Vaut 1 quand l''entrée devient strictement positive', ...
        {'vinit', 0, N}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Rise Positive'}, {});
    cat(end+1) = e('detectrisenonnegative', 'DetectRiseNonnegative', ...
        'Detect Rise Nonnegative', 'Logique', ...
        'Vaut 1 quand l''entrée devient positive ou nulle', ...
        {'vinit', 0, N}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Rise Nonnegative'}, {});
    cat(end+1) = e('detectfallnegative', 'DetectFallNegative', 'Detect Fall Negative', ...
        'Logique', 'Vaut 1 quand l''entrée devient strictement négative', ...
        {'vinit', 0, N}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Fall Negative'}, {});
    cat(end+1) = e('detectfallnonpositive', 'DetectFallNonpositive', ...
        'Detect Fall Nonpositive', 'Logique', ...
        'Vaut 1 quand l''entrée devient négative ou nulle', ...
        {'vinit', 0, N}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Fall Nonpositive'}, {});
    cat(end+1) = e('intervaltestdynamic', 'IntervalTestDynamic', 'Interval Test Dynamic', ...
        'Logique', 'Vaut 1 quand l''entrée u est entre les signaux lo et up', ...
        {'IntervalClosedRight', 'on', {'on', 'off'}; ...
         'IntervalClosedLeft', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Logic and Bit Operations/Interval Test Dynamic'}, {});
    cat(end+1) = e('bitwiseoperator', 'BitwiseOperator', 'Bitwise Operator', 'Logique', ...
        'Opère bit à bit sur des entiers, avec un masque ou entre ses entrées', ...
        {'logicop', 'AND', {'AND', 'OR', 'NAND', 'NOR', 'XOR', 'NOT'}; ...
         'UseBitMask', 'on', {'on', 'off'}; 'NumInputPorts', 1, N; 'BitMask', 217, N; ...
         'BitMaskRealWorld', 'Stored Integer', {'Stored Integer', 'Real World Value'}}, ...
        {'Operator', 'logicop'}, ...
        {'simulink/Logic and Bit Operations/Bitwise Operator'}, {});
    cat(end+1) = e('bitset', 'BitSet', 'Bit Set', 'Logique', ...
        'Met à 1 le bit iBit d''un entier, compté à partir de 0', ...
        {'iBit', 0, N}, {}, {'simulink/Logic and Bit Operations/Bit Set'}, {});
    cat(end+1) = e('bitclear', 'BitClear', 'Bit Clear', 'Logique', ...
        'Met à 0 le bit iBit d''un entier, compté à partir de 0', ...
        {'iBit', 0, N}, {}, {'simulink/Logic and Bit Operations/Bit Clear'}, {});
    cat(end+1) = e('shiftarithmetic', 'ArithShift', 'Shift Arithmetic', 'Logique', ...
        'Décale les bits d''un entier ; à droite, le signe se conserve', ...
        {'BitShiftNumber', 8, N; 'BitShiftDirection', 'Right', ...
         {'Left', 'Right', 'Bidirectional'}; 'BinPtShiftNumber', 0, N}, {}, ...
        {'simulink/Logic and Bit Operations/Shift Arithmetic'}, {});

    % --- Aiguillage ---
    cat(end+1) = e('intervaltest', 'IntervalTest', 'Interval Test', 'Logique', ...
        'Vaut 1 quand l''entrée est dans l''intervalle, bornes comprises ou non', ...
        {'IntervalClosedRight', 'on', {'on', 'off'}; 'uplimit', 0.5, N; ...
         'IntervalClosedLeft', 'on', {'on', 'off'}; 'lowlimit', -0.5, N; ...
         'OutDataTypeStr', 'boolean', {'boolean', 'double', 'single', 'int8', 'uint8', ...
         'int16', 'uint16', 'int32', 'uint32'}}, ...
        {'UpperLimit', 'uplimit'; 'LowerLimit', 'lowlimit'}, ...
        {'simulink/Logic and Bit Operations/Interval Test'}, {});
    cat(end+1) = e('manualswitch', 'ManualSwitch', 'Manual Switch', 'Aiguillage', ...
        'Rend l''une ou l''autre entrée, selon la position qu''on lui donne', ...
        {'sw', '1', {'1', '0'}}, {}, {'simulink/Signal Routing/Manual Switch'}, {});
    cat(end+1) = e('switch', 'Switch', 'Switch', 'Aiguillage', ...
        'Aiguille selon un seuil sur la deuxième entrée', ...
        {'Threshold', 0, N; 'Criteria', 'u2 >= Threshold', ...
         {'u2 >= Threshold', 'u2 > Threshold', 'u2 ~= 0'}; 'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Signal Routing/Switch', 'simulink/Commonly Used Blocks/Switch'}, {});
    cat(end+1) = e('multiportswitch', 'MultiPortSwitch', 'Multiport Switch', ...
        'Aiguillage', 'La première entrée choisit laquelle des suivantes passe', ...
        {'Inputs', 3, N; 'DataPortOrder', 'One-based contiguous', ...
         {'One-based contiguous', 'Zero-based contiguous', 'Specify indices'}; ...
         'DataPortIndices', '{1,2,3}', T; ...
         'DataPortForDefault', 'Last data port', {'Last data port', 'Additional data port'}; ...
         'DiagnosticForDefault', 'Error', {'Error', 'Warning', 'None'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Signal Routing/Multiport Switch', 'simulink/Signal Routing/Index Vector'}, ...
        {'indexvector'});
    cat(end+1) = e('busassignment', 'BusAssignment', 'Bus Assignment', 'Aiguillage', ...
        'Remplace des éléments d''un bus, désignés par leur nom, par ses autres entrées', ...
        {'AssignedSignals', 'signal1', T}, {}, {'simulink/Signal Routing/Bus Assignment'}, {});
    cat(end+1) = e('bustovector', 'BusToVector', 'Bus to Vector', 'Aiguillage', ...
        'Un bus de scalaires, devenu vecteur', {}, {}, ...
        {'simulink/Signal Attributes/Bus to Vector'}, {});
    cat(end+1) = e('environmentcontroller', 'EnvironmentController', ...
        'Environment Controller', 'Aiguillage', ...
        'Rend son entrée Sim en simulation ; l''entrée Coder ne sert qu''au code', {}, {}, ...
        {'simulink/Signal Routing/Environment Controller'}, {});
    % Un bus : des signaux réunis sous leurs noms, qu'un Bus Selector
    % reprend par ces noms — « vitesse », ou « mesures.vitesse » dans un
    % bus emboîté. Inputs vaut un nombre (les éléments s'appellent alors
    % signal1, signal2...) ou la liste des noms, « vitesse,position ».
    cat(end+1) = e('buscreator', 'BusCreator', 'Bus Creator', 'Aiguillage', ...
        'Réunit ses entrées en un bus, chaque élément sous son nom', ...
        {'Inputs', '2', T; 'OutDataTypeStr', 'Inherit: auto', T}, {}, ...
        {'simulink/Signal Routing/Bus Creator', ...
         'simulink/Commonly Used Blocks/Bus Creator'}, {});
    cat(end+1) = e('busselector', 'BusSelector', 'Bus Selector', 'Aiguillage', ...
        'Reprend des éléments d''un bus par leur nom', ...
        {'OutputSignals', 'signal1,signal2', T; 'OutputAsBus', 'off', {'off', 'on'}}, {}, ...
        {'simulink/Signal Routing/Bus Selector', ...
         'simulink/Commonly Used Blocks/Bus Selector'}, {});
    cat(end+1) = e('datastorememory', 'DataStoreMemory', 'Data Store Memory', ...
        'Aiguillage', 'Une mémoire partagée, que lisent et écrivent les blocs de son nom', ...
        {'DataStoreName', 'A', T; 'InitialValue', 0, N}, {}, ...
        {'simulink/Signal Routing/Data Store Memory'}, {});
    cat(end+1) = e('datastoreread', 'DataStoreRead', 'Data Store Read', 'Aiguillage', ...
        'Lit la mémoire partagée de son nom', ...
        {'DataStoreName', 'A', T; 'SampleTime', 0, N}, {}, ...
        {'simulink/Signal Routing/Data Store Read'}, {});
    cat(end+1) = e('datastorewrite', 'DataStoreWrite', 'Data Store Write', 'Aiguillage', ...
        'Écrit son entrée dans la mémoire partagée de son nom', ...
        {'DataStoreName', 'A', T; 'SampleTime', -1, N}, {}, ...
        {'simulink/Signal Routing/Data Store Write'}, {});
    cat(end+1) = e('ratetransition', 'RateTransition', 'Rate Transition', 'Aiguillage', ...
        'Passe d''une période à l''autre : tenue vers le lent, retard vers le rapide', ...
        {'Integrity', 'on', {'on', 'off'}; 'Deterministic', 'on', {'on', 'off'}; ...
         'X0', 0, N; 'OutPortSampleTime', -1, N}, {'InitialCondition', 'X0'}, ...
        {'simulink/Signal Attributes/Rate Transition'}, {});
    cat(end+1) = e('ic', 'InitialCondition', 'IC', 'Aiguillage', ...
        'Rend sa valeur au premier instant, puis son entrée', ...
        {'Value', 1, N}, {}, {'simulink/Signal Attributes/IC'}, {'initialcondition'});
    cat(end+1) = e('width', 'Width', 'Width', 'Aiguillage', ...
        'Le nombre d''éléments de son entrée', {}, {}, ...
        {'simulink/Signal Attributes/Width'}, {});
    cat(end+1) = e('mux', 'Mux', 'Mux', 'Aiguillage', ...
        'Réunit ses entrées en un vecteur', ...
        {'Inputs', 2, N}, {}, ...
        {'simulink/Signal Routing/Mux', 'simulink/Commonly Used Blocks/Mux'}, {});
    cat(end+1) = e('demux', 'Demux', 'Demux', 'Aiguillage', ...
        'Sépare un vecteur en ses parties', ...
        {'Outputs', 2, N}, {}, ...
        {'simulink/Signal Routing/Demux', 'simulink/Commonly Used Blocks/Demux'}, {});
    cat(end+1) = e('assignment', 'Assignment', 'Assignment', 'Aiguillage', ...
        'Remplace des éléments de Y0 par ceux de U, à des indices donnés', ...
        {'NumberOfDimensions', 1, N; 'IndexMode', 'One-based', {'One-based', 'Zero-based'}; ...
         'IndexOptionArray', {'Index vector (dialog)'}, 'libre'; ...
         'IndexParamArray', {'1'}, 'libre'; ...
         'OutputInitialize', 'Initialize using input port <Y0>', ...
         {'Initialize using input port <Y0>', 'Specify size for each dimension in table'}; ...
         'OutputSizeArray', {'1'}, 'libre'}, {}, ...
        {'simulink/Math Operations/Assignment'}, {});
    cat(end+1) = e('signalspecification', 'SignalSpecification', 'Signal Specification', ...
        'Aiguillage', 'Laisse passer son entrée en vérifiant ses dimensions et son type', ...
        {'Dimensions', -1, N; 'SampleTime', -1, N; 'OutDataTypeStr', 'Inherit: auto', T; ...
         'OutMin', [], N; 'OutMax', [], N; 'Unit', 'inherit', T; ...
         'SignalType', 'auto', {'auto', 'real', 'complex'}}, {}, ...
        {'simulink/Signal Attributes/Signal Specification'}, {});
    cat(end+1) = e('selector', 'Selector', 'Selector', 'Aiguillage', ...
        'Choisit des éléments de son entrée par leurs indices', ...
        {'Indices', 1, N; 'InputPortWidth', -1, N}, {}, ...
        {'simulink/Signal Routing/Selector'}, {});
    cat(end+1) = e('concatenate', 'Concatenate', 'Vector Concatenate', 'Aiguillage', ...
        'Met ses entrées bout à bout', ...
        {'NumInputs', 2, N; 'Mode', 'Vector', {'Vector', 'Multidimensional array'}; ...
         'ConcatenateDimension', 1, N}, {}, ...
        {'simulink/Math Operations/Vector Concatenate', ...
         'simulink/Math Operations/Matrix Concatenate', ...
         'simulink/Signal Routing/Vector Concatenate'}, ...
        {'vectorconcatenate', 'matrixconcatenate'});
    cat(end+1) = e('reshape', 'Reshape', 'Reshape', 'Aiguillage', ...
        'Change les dimensions de son entrée', ...
        {'OutputDimensionality', '1-D array', ...
         {'1-D array', 'Column vector (2-D)', 'Row vector (2-D)', 'Customize'}; ...
         'OutputDimensions', [1 1], N}, {}, ...
        {'simulink/Math Operations/Reshape'}, {});
    cat(end+1) = e('goto', 'Goto', 'Goto', 'Aiguillage', ...
        'Envoie son entrée aux blocs From de même étiquette', ...
        {'GotoTag', 'A', T; 'TagVisibility', 'local', {'local', 'scoped', 'global'}}, ...
        {}, {'simulink/Signal Routing/Goto'}, {});
    cat(end+1) = e('from', 'From', 'From', 'Aiguillage', ...
        'Rend le signal du bloc Goto de même étiquette', ...
        {'GotoTag', 'A', T}, {}, {'simulink/Signal Routing/From'}, {});
    % NombreDePorts n'est pas un réglage de Simulink : c'est le dépliage
    % d'un sous-système à plusieurs sorties qui le pose, le bloc laissant
    % alors passer chaque entrée vers la sortie de même rang.
    cat(end+1) = e('signalconversion', 'SignalConversion', 'Signal Conversion', ...
        'Aiguillage', 'Laisse passer son entrée', ...
        {'ConversionOutput', 'Signal copy', {'Signal copy', 'Virtual bus', ...
         'Nonvirtual bus'}; 'NombreDePorts', 1, N; 'OutDataTypeStr', 'Inherit: auto', T}, ...
        {}, ...
        {'simulink/Signal Attributes/Signal Conversion'}, {});

    % --- Continu ---
    cat(end+1) = e('integrator', 'Integrator', 'Integrator', 'Continu', ...
        'Intègre : 1/s, bornes, remise et condition initiale externes', ...
        {'InitialCondition', 0, N; 'LimitOutput', 'off', {'on', 'off'}; ...
         'UpperSaturationLimit', Inf, N; 'LowerSaturationLimit', -Inf, N; ...
         'ExternalReset', 'none', {'none', 'rising', 'falling', 'either', 'level', ...
                                   'level hold'}; ...
         'InitialConditionSource', 'internal', {'internal', 'external'}; ...
         'ShowSaturationPort', 'off', {'on', 'off'}; 'ShowStatePort', 'off', {'on', 'off'}; ...
         'ZeroCross', 'on', {'on', 'off'}}, ...
        {'X0', 'InitialCondition'}, ...
        {'simulink/Continuous/Integrator', 'simulink/Commonly Used Blocks/Integrator', ...
         'simulink/Continuous/Integrator Limited'}, ...
        {'integratorlimited'});
    cat(end+1) = e('secondorderintegrator', 'SecondOrderIntegrator', ...
        'Second-Order Integrator', 'Continu', ...
        'Intègre deux fois : x et dx/dt, d''une entrée d2x/dt2', ...
        {'ICX', 0, N; 'ICDXDT', 0, N}, {}, ...
        {'simulink/Continuous/Integrator, Second-Order'}, ...
        {'integratorsecond-order', 'second-orderintegrator'});
    cat(end+1) = e('derivative', 'Derivative', 'Derivative', 'Continu', ...
        'Dérive : du/dt', {}, {}, {'simulink/Continuous/Derivative'}, {});
    cat(end+1) = e('transferfcn', 'TransferFcn', 'Transfer Fcn', 'Continu', ...
        'Une transmittance en s', ...
        {'Numerator', 1, N; 'Denominator', [1 1], N}, {}, ...
        {'simulink/Continuous/Transfer Fcn'}, {});
    cat(end+1) = e('statespace', 'StateSpace', 'State-Space', 'Continu', ...
        'Une représentation d''état, à plusieurs voies', ...
        {'A', 0, N; 'B', 0, N; 'C', 1, N; 'D', 0, N; 'X0', [], N}, ...
        {'InitialCondition', 'X0'}, {'simulink/Continuous/State-Space'}, {});
    cat(end+1) = e('zeropole', 'ZeroPole', 'Zero-Pole', 'Continu', ...
        'Une transmittance donnée par ses zéros, ses pôles et son gain', ...
        {'Zeros', [], N; 'Poles', -1, N; 'Gain', 1, N}, {}, ...
        {'simulink/Continuous/Zero-Pole'}, {});
    cat(end+1) = e('transportdelay', 'TransportDelay', 'Transport Delay', 'Continu', ...
        'Retarde le signal d''une durée', ...
        {'DelayTime', 1, N; 'InitialOutput', 0, N; 'BufferSize', 1024, N}, {}, ...
        {'simulink/Continuous/Transport Delay'}, {});
    methodes = {'Forward Euler', 'Backward Euler', 'Trapezoidal'};
    cat(end+1) = e('variabletransportdelay', 'VariableTransportDelay', ...
        'Variable Transport Delay', 'Continu', ...
        'Retarde u de la durée que donne sa seconde entrée', ...
        {'VariableDelayType', 'Variable transport delay', {'Variable transport delay', ...
         'Variable time delay'}; 'MaximumDelay', 10, N; 'InitialOutput', 0, N; ...
         'MaximumPoints', 1024, N; 'ZeroDelay', 'off', {'on', 'off'}}, {}, ...
        {'simulink/Continuous/Variable Transport Delay', ...
         'simulink/Continuous/Variable Time Delay'}, {'variabletimedelay'});
    cat(end+1) = e('pidcontroller', 'PIDController', 'PID Controller', 'Continu', ...
        'Un PID, continu ou discret, parallèle ou idéal, borné, à remise', ...
        {'P', 1, N; 'I', 1, N; 'D', 0, N; 'N', 100, N; ...
         'InitialConditionForIntegrator', 0, N; 'InitialConditionForFilter', 0, N; ...
         'Form', 'Parallel', {'Parallel', 'Ideal'}; ...
         'Controller', 'PID', {'PID', 'PI', 'PD', 'P', 'I'}; ...
         'TimeDomain', 'Continuous-time', {'Continuous-time', 'Discrete-time'}; ...
         'SampleTime', -1, N; 'IntegratorMethod', 'Forward Euler', methodes; ...
         'FilterMethod', 'Forward Euler', methodes; 'UseFilter', 'on', {'on', 'off'}; ...
         'InitialConditionSource', 'internal', {'internal', 'external'}; ...
         'ExternalReset', 'none', {'none', 'rising', 'falling', 'either', 'level'}; ...
         'LimitOutput', 'off', {'on', 'off'}; 'UpperSaturationLimit', Inf, N; ...
         'LowerSaturationLimit', -Inf, N; ...
         'AntiWindupMode', 'none', {'none', 'back-calculation', 'clamping'}; 'Kb', 1, N}, {}, ...
        {'simulink/Continuous/PID Controller', 'simulink/Discrete/Discrete PID Controller'}, ...
        {'pid', 'discretepidcontroller'});

    % --- Discret ---
    cat(end+1) = e('delay', 'Delay', 'Delay', 'Discret', ...
        'Retarde de N pas : z^-N ; longueur par une entrée, activation, remise', ...
        {'InitialCondition', 0, N; 'DelayLength', 1, N; 'SampleTime', [], N; ...
         'DelayLengthSource', 'Dialog', {'Dialog', 'Input port'}; ...
         'DelayLengthUpperLimit', 100, N; ...
         'InitialConditionSource', 'Dialog', {'Dialog', 'Input port'}; ...
         'ExternalReset', 'None', {'None', 'Rising', 'Falling', 'Either', 'Level', ...
                                   'Level hold'}; ...
         'ShowEnablePort', 'off', {'on', 'off'}}, ...
        {'X0', 'InitialCondition'}, ...
        {'simulink/Discrete/Delay', 'simulink/Discrete/Unit Delay', ...
         'simulink/Commonly Used Blocks/Unit Delay', 'simulink/Discrete/Resettable Delay', ...
         'simulink/Discrete/Enabled Delay', 'simulink/Discrete/Variable Integer Delay'}, ...
        {'unitdelay', 'resettabledelay', 'enableddelay', 'variableintegerdelay'});
    cat(end+1) = e('memory', 'Memory', 'Memory', 'Discret', ...
        'La valeur de l''entrée au pas précédent', ...
        {'InitialCondition', 0, N}, {'X0', 'InitialCondition'}, ...
        {'simulink/Discrete/Memory'}, {});
    cat(end+1) = e('zoh', 'ZeroOrderHold', 'Zero-Order Hold', 'Discret', ...
        'Tenue d''ordre zéro ; période par défaut : dix pas', ...
        {'SampleTime', [], N}, {}, {'simulink/Discrete/Zero-Order Hold'}, ...
        {'zeroorderhold'});
    cat(end+1) = e('discreteintegrator', 'DiscreteIntegrator', ...
        'Discrete-Time Integrator', 'Discret', ...
        'Intègre ou accumule à période fixe ; bornes, remise, condition initiale externe', ...
        {'Gain', 1, N; 'SampleTime', [], N; 'IntegratorMethod', 'ForwardEuler', ...
         {'ForwardEuler', 'BackwardEuler', 'Trapezoidal', ...
          'Integration: Forward Euler', 'Integration: Backward Euler', ...
          'Integration: Trapezoidal', 'Accumulation: Forward Euler', ...
          'Accumulation: Backward Euler', 'Accumulation: Trapezoidal'}; ...
         'InitialCondition', 0, N; ...
         'InitialConditionSource', 'internal', {'internal', 'external'}; ...
         'ExternalReset', 'none', {'none', 'rising', 'falling', 'either', 'level', ...
                                   'sampled level'}; ...
         'LimitOutput', 'off', {'on', 'off'}; 'UpperSaturationLimit', Inf, N; ...
         'LowerSaturationLimit', -Inf, N; 'ShowSaturationPort', 'off', {'on', 'off'}; ...
         'ShowStatePort', 'off', {'on', 'off'}}, ...
        {'gainval', 'Gain'}, {'simulink/Discrete/Discrete-Time Integrator'}, ...
        {'discrete-timeintegrator'});
    cat(end+1) = e('discretetransferfcn', 'DiscreteTransferFcn', ...
        'Discrete Transfer Fcn', 'Discret', 'Une transmittance en z', ...
        {'Numerator', 1, N; 'Denominator', [1 0.5], N; 'SampleTime', [], N}, {}, ...
        {'simulink/Discrete/Discrete Transfer Fcn'}, {});
    cat(end+1) = e('discretefilter', 'DiscreteFilter', 'Discrete Filter', 'Discret', ...
        'Un filtre en puissances croissantes de z^-1', ...
        {'Numerator', 1, N; 'Denominator', [1 0.5], N; 'SampleTime', [], N}, {}, ...
        {'simulink/Discrete/Discrete Filter'}, {});
    cat(end+1) = e('firstorderhold', 'FirstOrderHold', 'First-Order Hold', 'Discret', ...
        'Prolonge en ligne droite les deux derniers échantillons, pris toutes les Ts', ...
        {'Ts', 1, N}, {'SampleTime', 'Ts'}, {'simulink/Discrete/First-Order Hold'}, {});
    cat(end+1) = e('discretefirfilter', 'DiscreteFir', 'Discrete FIR Filter', 'Discret', ...
        'Un filtre à réponse impulsionnelle finie : ses coefficients en puissances de z^-1', ...
        {'Coefficients', [0.5 0.5], N; 'FilterStructure', 'Direct form', ...
         {'Direct form', 'Direct form symmetric', 'Direct form antisymmetric', ...
          'Direct form transposed'}; 'InitialStates', 0, N; 'SampleTime', -1, N}, {}, ...
        {'simulink/Discrete/Discrete FIR Filter'}, {'discretefir'});
    cat(end+1) = e('transferfcnfirstorder', 'TransferFcnFirstOrder', ...
        'Transfer Fcn First Order', 'Discret', ...
        '(1 - p) z / (z - p) : un premier ordre discret de gain statique 1', ...
        {'PoleZ', 0.95, N; 'ICPrevOutput', 0, N}, {}, ...
        {'simulink/Discrete/Transfer Fcn First Order'}, {});
    cat(end+1) = e('transferfcnleadorlag', 'TransferFcnLeadOrLag', ...
        'Transfer Fcn Lead or Lag', 'Discret', ...
        'K (z - zéro) / (z - pôle) : une avance ou un retard de phase', ...
        {'PoleZ', 0.95, N; 'ZeroZ', 0.75, N; 'Gain', 1, N; 'ICPrevOutput', 0, N; ...
         'ICPrevInput', 0, N}, {}, {'simulink/Discrete/Transfer Fcn Lead or Lag'}, {});
    cat(end+1) = e('transferfcnrealzero', 'TransferFcnRealZero', 'Transfer Fcn Real Zero', ...
        'Discret', '(z - zéro) / z : un zéro réel', ...
        {'ZeroZ', 0.75, N; 'ICPrevInput', 0, N}, {}, ...
        {'simulink/Discrete/Transfer Fcn Real Zero'}, {});
    cat(end+1) = e('discretezeropole', 'DiscreteZeroPole', 'Discrete Zero-Pole', ...
        'Discret', 'Une transmittance en z, par ses zéros, ses pôles et son gain', ...
        {'Zeros', 1, N; 'Poles', [0 0.5], N; 'Gain', 1, N; 'SampleTime', [], N}, {}, ...
        {'simulink/Discrete/Discrete Zero-Pole'}, {});
    cat(end+1) = e('discretederivative', 'DiscreteDerivative', 'Discrete Derivative', ...
        'Discret', 'K (u - u d''avant) / Ts : la dérivée à la période du bloc', ...
        {'gainval', 1, N; 'ICPrevScaledInput', 0, N; 'SampleTime', -1, N}, ...
        {'Gain', 'gainval'}, {'simulink/Discrete/Discrete Derivative'}, {});
    cat(end+1) = e('difference', 'Difference', 'Difference', 'Discret', ...
        'u - u d''avant : l''écart entre deux instants', ...
        {'ICPrevInput', 0, N}, {'InitialCondition', 'ICPrevInput'}, ...
        {'simulink/Discrete/Difference'}, {});
    cat(end+1) = e('tappeddelay', 'TappedDelay', 'Tapped Delay', 'Discret', ...
        'Les N dernières valeurs de l''entrée, en un vecteur', ...
        {'vinit', 0, N; 'samptime', -1, N; 'NumDelays', 4, N; ...
         'DelayOrder', 'Oldest', {'Oldest', 'Newest'}; 'includeCurrent', 'off', {'on', 'off'}}, ...
        {'InitialCondition', 'vinit'; 'SampleTime', 'samptime'}, ...
        {'simulink/Discrete/Tapped Delay'}, {});
    cat(end+1) = e('discretestatespace', 'DiscreteStateSpace', ...
        'Discrete State-Space', 'Discret', ...
        'Une représentation d''état échantillonnée, à plusieurs voies', ...
        {'A', 0, N; 'B', 0, N; 'C', 1, N; 'D', 0, N; 'X0', [], N; 'SampleTime', [], N}, ...
        {'InitialCondition', 'X0'}, {'simulink/Discrete/Discrete State-Space'}, {});

    % --- Sorties ---
    cat(end+1) = e('outport', 'Outport', 'Out1', 'Sorties', ...
        'La sortie du modèle, vue par LINMOD', ...
        {'Port', 1, N; 'InitialOutput', 0, N; ...
         'OutputWhenDisabled', 'held', {'held', 'reset'}; ...
         'OutDataTypeStr', 'Inherit: auto', T; ...
         'SignalType', 'auto', {'auto', 'real', 'complex'}}, {}, ...
        {'simulink/Sinks/Out1', 'simulink/Ports & Subsystems/Out1', ...
         'simulink/Commonly Used Blocks/Out1'}, {'out1', 'out'});
    cat(end+1) = e('scope', 'Scope', 'Scope', 'Sorties', ...
        'Un oscilloscope : chaque entrée est relevée', ...
        {'NumInputPorts', 1, N}, {}, ...
        {'simulink/Sinks/Scope', 'simulink/Commonly Used Blocks/Scope'}, {});
    cat(end+1) = e('display', 'Display', 'Display', 'Sorties', ...
        'Affiche la valeur de son entrée', ...
        {'Format', 'short', {'short', 'long', 'short_e', 'long_e', 'bank', 'hex'}}, {}, ...
        {'simulink/Sinks/Display'}, {});
    cat(end+1) = e('xygraph', 'XYGraph', 'XY Graph', 'Sorties', ...
        'Relève y en fonction de x : ses deux entrées', ...
        {'xmin', -1, N; 'xmax', 1, N; 'ymin', -1, N; 'ymax', 1, N; 'st', -1, N}, {}, ...
        {'simulink/Sinks/XY Graph'}, {});
    cat(end+1) = e('tofile', 'ToFile', 'To File', 'Sorties', ...
        'Écrit le temps et le signal dans un fichier MAT, en fin de simulation', ...
        {'Filename', 'untitled.mat', T; 'MatrixName', 'ans', T; 'Decimation', 1, N; ...
         'SampleTime', -1, N; 'SaveFormat', 'Array', {'Array'}}, {}, ...
        {'simulink/Sinks/To File'}, {});
    cat(end+1) = e('toworkspace', 'ToWorkspace', 'To Workspace', 'Sorties', ...
        'Dépose le signal dans l''espace de travail', ...
        {'VariableName', 'simout', T; 'SaveFormat', 'Array', ...
         {'Array', 'Structure With Time', 'Structure', 'Timeseries'}}, {}, ...
        {'simulink/Sinks/To Workspace'}, {});
    cat(end+1) = e('terminator', 'Terminator', 'Terminator', 'Sorties', ...
        'Ferme une sortie qu''on ne lit pas', {}, {}, ...
        {'simulink/Sinks/Terminator', 'simulink/Commonly Used Blocks/Terminator'}, {});
    cat(end+1) = e('stopsimulation', 'Stop', 'Stop Simulation', 'Sorties', ...
        'Arrête la simulation dès que son entrée n''est plus nulle', {}, {}, ...
        {'simulink/Sinks/Stop Simulation'}, {'stop'});
    cat(end+1) = e('assertion', 'Assertion', 'Assertion', 'Sorties', ...
        'Échoue dès que son entrée s''annule', ...
        {'Enabled', 'on', {'on', 'off'}; 'StopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {}, {'simulink/Model Verification/Assertion'}, {});
    cat(end+1) = e('checkstaticrange', 'CheckStaticRange', 'Check Static Range', 'Sorties', ...
        'Échoue quand l''entrée sort de [min, max]', ...
        {'max', 100, N; 'max_included', 'on', {'on', 'off'}; 'min', 0, N; ...
         'min_included', 'on', {'on', 'off'}; ...
         'enabled', 'on', {'on', 'off'}; 'stopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {'Enabled', 'enabled'; 'StopWhenAssertionFail', 'stopWhenAssertionFail'}, ...
        {'simulink/Model Verification/Check Static Range'}, {});
    cat(end+1) = e('checkstaticlowerbound', 'CheckStaticLowerBound', ...
        'Check Static Lower Bound', 'Sorties', ...
        'Échoue quand l''entrée passe sous min', ...
        {'min', 0, N; ...
         'min_included', 'on', {'on', 'off'}; ...
         'enabled', 'on', {'on', 'off'}; 'stopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {'Enabled', 'enabled'; 'StopWhenAssertionFail', 'stopWhenAssertionFail'}, ...
        {'simulink/Model Verification/Check Static Lower Bound'}, {});
    cat(end+1) = e('checkstaticupperbound', 'CheckStaticUpperBound', ...
        'Check Static Upper Bound', 'Sorties', ...
        'Échoue quand l''entrée passe au-dessus de max', ...
        {'max', 0, N; 'max_included', 'on', {'on', 'off'}; ...
         'enabled', 'on', {'on', 'off'}; 'stopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {'Enabled', 'enabled'; 'StopWhenAssertionFail', 'stopWhenAssertionFail'}, ...
        {'simulink/Model Verification/Check Static Upper Bound'}, {});
    cat(end+1) = e('checkstaticgap', 'CheckStaticGap', 'Check Static Gap', 'Sorties', ...
        'Échoue quand l''entrée tombe dans l''intervalle ]min, max[', ...
        {'max', 100, N; 'max_included', 'on', {'on', 'off'}; 'min', 0, N; ...
         'min_included', 'on', {'on', 'off'}; ...
         'enabled', 'on', {'on', 'off'}; 'stopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {'Enabled', 'enabled'; 'StopWhenAssertionFail', 'stopWhenAssertionFail'}, ...
        {'simulink/Model Verification/Check Static Gap'}, {});
    cat(end+1) = e('checkdynamicrange', 'CheckDynamicRange', 'Check Dynamic Range', 'Sorties', ...
        'Échoue quand sig sort de ]min, max[, bornes données par des signaux', ...
        {'enabled', 'on', {'on', 'off'}; ...
         'stopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {'Enabled', 'enabled'; 'StopWhenAssertionFail', 'stopWhenAssertionFail'}, ...
        {'simulink/Model Verification/Check Dynamic Range'}, {});
    cat(end+1) = e('checkdynamiclowerbound', 'CheckDynamicLowerBound', ...
        'Check Dynamic Lower Bound', 'Sorties', ...
        'Échoue quand sig n''est plus au-dessus du signal min', ...
        {'enabled', 'on', {'on', 'off'}; ...
         'stopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {'Enabled', 'enabled'; 'StopWhenAssertionFail', 'stopWhenAssertionFail'}, ...
        {'simulink/Model Verification/Check Dynamic Lower Bound'}, {});
    cat(end+1) = e('checkdynamicupperbound', 'CheckDynamicUpperBound', ...
        'Check Dynamic Upper Bound', 'Sorties', ...
        'Échoue quand sig n''est plus au-dessous du signal max', ...
        {'enabled', 'on', {'on', 'off'}; ...
         'stopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {'Enabled', 'enabled'; 'StopWhenAssertionFail', 'stopWhenAssertionFail'}, ...
        {'simulink/Model Verification/Check Dynamic Upper Bound'}, {});
    cat(end+1) = e('checkdynamicgap', 'CheckDynamicGap', 'Check Dynamic Gap', 'Sorties', ...
        'Échoue quand sig tombe entre les signaux min et max', ...
        {'enabled', 'on', {'on', 'off'}; ...
         'stopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {'Enabled', 'enabled'; 'StopWhenAssertionFail', 'stopWhenAssertionFail'}, ...
        {'simulink/Model Verification/Check Dynamic Gap'}, {});

    % --- Fonctions de l'utilisateur ---
    cat(end+1) = e('fcn', 'Fcn', 'Fcn', 'Fonctions', ...
        'Une expression de l''entrée u, écrite comme en MATLAB : u(1)*sin(u(2))', ...
        {'Expr', 'sin(u(1)*exp(2.3*(-u(2))))', T; 'SampleTime', -1, N}, {}, ...
        {'simulink/User-Defined Functions/Fcn'}, {});
    cat(end+1) = e('matlabfunction', 'MATLABFunction', 'MATLAB Function', 'Fonctions', ...
        'Une fonction MATLAB : ses arguments sont les entrées, ses sorties les sorties', ...
        {'Script', sprintf('function y = fcn(u)\ny = u;'), T; 'SampleTime', -1, N}, {}, ...
        {'simulink/User-Defined Functions/MATLAB Function'}, {'emlblock'});
    cat(end+1) = e('interpretedmatlabfunction', 'MATLABFcn', ...
        'Interpreted MATLAB Function', 'Fonctions', ...
        'Une fonction MATLAB appliquée à l''entrée : un nom, ou une expression de u', ...
        {'MATLABFcn', 'sin', T; 'OutputDimensions', -1, N; 'SampleTime', -1, N}, {}, ...
        {'simulink/User-Defined Functions/Interpreted MATLAB Function'}, ...
        {'matlabfcn'});
    cat(end+1) = e('sfunction', 'S-Function', 'S-Function', 'Fonctions', ...
        'Une S-fonction de niveau 1 écrite en MATLAB : [sys,x0,str,ts] = f(t,x,u,flag)', ...
        {'FunctionName', 'system', T; 'Parameters', '', T}, {}, ...
        {'simulink/User-Defined Functions/S-Function'}, {'sfun'});
    cat(end+1) = e('msfunction', 'M-S-Function', 'Level-2 MATLAB S-Function', 'Fonctions', ...
        'Une S-fonction de niveau 2 écrite en MATLAB : setup(block), puis ses méthodes', ...
        {'FunctionName', '', T; 'Parameters', '', T}, {}, ...
        {'simulink/User-Defined Functions/Level-2 MATLAB S-Function'}, ...
        {'level2sfunction', 'm-s-function'});

    % --- Stateflow ---
    cat(end+1) = e('chart', 'Chart', 'Chart', 'Stateflow', ...
        'Une machine à états de Stateflow (SFCHART), qui fait un pas à chaque instant', ...
        {'Chart', [], 'libre'; 'Inputs', 1, N; 'Outputs', {'etat'}, 'libre'; ...
         'InitialContext', struct(), 'libre'; 'SampleTime', -1, N}, {}, ...
        {'sflib/Chart', 'simulink/Stateflow/Chart'}, {'stateflow'});

    % --- Sous-systèmes ---
    cat(end+1) = e('subsystem', 'SubSystem', 'Subsystem', 'Sous-systèmes', ...
        'Un schéma entier abrégé en un bloc', ...
        {'Model', [], 'modele'; 'Mask', 'off', {'off', 'on'}; 'MaskVariables', '', T; ...
         'MaskValueString', '', T; 'MaskPrompts', {}, 'libre'; ...
         'Variant', 'off', {'off', 'on'}; 'VariantControl', '', T; ...
         'VariantControlMode', 'expression', {'expression', 'label'}; ...
         'LabelModeActiveChoice', '', T; 'AllowZeroVariantControls', 'off', {'off', 'on'}}, ...
        {'Modele', 'Model'}, ...
        {'simulink/Ports & Subsystems/Subsystem', ...
         'simulink/Commonly Used Blocks/Subsystem', ...
         'simulink/Ports & Subsystems/Enabled Subsystem', ...
         'simulink/Ports & Subsystems/Triggered Subsystem', ...
         'simulink/Ports & Subsystems/Enabled and Triggered Subsystem', ...
         'simulink/Ports & Subsystems/If Action Subsystem', ...
         'simulink/Ports & Subsystems/Switch Case Action Subsystem', ...
         'simulink/Ports & Subsystems/Function-Call Subsystem', ...
         'simulink/Ports & Subsystems/For Iterator Subsystem', ...
         'simulink/Ports & Subsystems/While Iterator Subsystem', ...
         'simulink/Ports & Subsystems/Variant Subsystem'}, ...
        {'variantsubsystem', 'enabledsubsystem', 'triggeredsubsystem', ...
         'enabledandtriggeredsubsystem', ...
         'ifactionsubsystem', 'switchcaseactionsubsystem', 'function-callsubsystem', ...
         'foriteratorsubsystem', 'whileiteratorsubsystem'});
    cat(end+1) = e('modelreference', 'ModelReference', 'Model', 'Sous-systèmes', ...
        'Un autre modèle, relu à chaque simulation, abrégé en un bloc', ...
        {'ModelName', '', T; 'VariantControl', '', T}, {'ModelFile', 'ModelName'}, ...
        {'simulink/Ports & Subsystems/Model'}, {'model'});
    cat(end+1) = e('iterateur', 'MatLibreIterateur', 'Iterateur', 'Interne', ...
        'Interne : un sous-système itéré, qui calcule son modèle plusieurs fois par pas', ...
        {'Model', [], 'modele'}, {}, {}, {});
    % Les ports de contrôle se posent dans un sous-système : ils en font un
    % sous-système conditionnel, qui ne calcule que quand son entrée de
    % contrôle le permet, et tient ses sorties le reste du temps.
    cat(end+1) = e('enableport', 'EnablePort', 'Enable', 'Sous-systèmes', ...
        'Dans un sous-système : il ne calcule que quand ce port reçoit un signal positif', ...
        {'StatesWhenEnabling', 'held', {'held', 'reset'}; ...
         'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Ports & Subsystems/Enable'}, {'enable'});
    cat(end+1) = e('triggerport', 'TriggerPort', 'Trigger', 'Sous-systèmes', ...
        'Dans un sous-système : il ne calcule qu''au front du signal de ce port', ...
        {'TriggerType', 'rising', {'rising', 'falling', 'either', 'function-call'}; ...
         'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Ports & Subsystems/Trigger'}, {'trigger'});
    cat(end+1) = e('foriterator', 'ForIterator', 'For Iterator', 'Sous-systèmes', ...
        'Dans un sous-système : il y calcule N fois par pas, et rend le rang', ...
        {'IterationSource', 'internal', {'internal', 'external'}; ...
         'IterationLimit', 5, N; 'ShowIterationPort', 'on', {'on', 'off'}; ...
         'IndexMode', 'One-based', {'One-based', 'Zero-based'}; ...
         'ResetStates', 'held', {'held', 'reset'}}, {}, ...
        {'simulink/Ports & Subsystems/For Iterator'}, {});
    cat(end+1) = e('whileiterator', 'WhileIterator', 'While Iterator', 'Sous-systèmes', ...
        'Dans un sous-système : il y calcule tant que son entrée cond est vraie', ...
        {'WhileBlockType', 'while', {'while', 'do-while'}; 'MaxIters', 5, N; ...
         'ShowIterationPort', 'off', {'on', 'off'}; ...
         'ResetStates', 'held', {'held', 'reset'}}, {}, ...
        {'simulink/Ports & Subsystems/While Iterator'}, {});
    cat(end+1) = e('functioncallgenerator', 'FunctionCallGenerator', ...
        'Function-Call Generator', 'Sous-systèmes', ...
        'Appelle le sous-système relié à son port, à chaque instant de sa période', ...
        {'sample_time', 1, N; 'numberOfIterations', 1, N}, {'SampleTime', 'sample_time'}, ...
        {'simulink/Ports & Subsystems/Function-Call Generator'}, {'function-callgenerator'});
    cat(end+1) = e('actionport', 'ActionPort', 'Action Port', 'Sous-systèmes', ...
        'Dans un sous-système : il calcule quand un bloc If ou Switch Case le désigne', ...
        {'InitializeStates', 'held', {'held', 'reset'}}, {}, ...
        {'simulink/Ports & Subsystems/Action Port'}, {'action'});
    cat(end+1) = e('if', 'If', 'If', 'Sous-systèmes', ...
        'Choisit, par des conditions sur ses entrées u1, u2..., le sous-système d''action qui calcule', ...
        {'NumInputs', 1, N; 'IfExpression', 'u1 > 0', T; 'ElseIfExpressions', '', T; ...
         'ShowElse', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Ports & Subsystems/If'}, {});
    cat(end+1) = e('switchcase', 'SwitchCase', 'Switch Case', 'Sous-systèmes', ...
        'Choisit, selon la valeur entière de son entrée, le sous-système d''action qui calcule', ...
        {'CaseConditions', '{1}', T; 'ShowDefaultCase', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Ports & Subsystems/Switch Case'}, {});
    % Les variantes d'un signal : une seule entrée passe — Variant Source —,
    % ou une seule sortie reçoit — Variant Sink —, celle dont la condition
    % est vraie au moment de simuler.
    cat(end+1) = e('variantsource', 'VariantSource', 'Variant Source', 'Aiguillage', ...
        'Laisse passer celle de ses entrées dont la condition est vraie', ...
        {'VariantControls', {'V == 1', 'V == 2'}, 'libre'; ...
         'VariantControlMode', 'expression', {'expression', 'label'}; ...
         'LabelModeActiveChoice', '', T; 'AllowZeroVariantControls', 'off', {'off', 'on'}}, ...
        {}, {'simulink/Signal Routing/Variant Source'}, {});
    cat(end+1) = e('variantsink', 'VariantSink', 'Variant Sink', 'Aiguillage', ...
        'Envoie son entrée à celle de ses sorties dont la condition est vraie', ...
        {'VariantControls', {'V == 1', 'V == 2'}, 'libre'; ...
         'VariantControlMode', 'expression', {'expression', 'label'}; ...
         'LabelModeActiveChoice', '', T; 'AllowZeroVariantControls', 'off', {'off', 'on'}}, ...
        {}, {'simulink/Signal Routing/Variant Sink'}, {});
    cat(end+1) = e('merge', 'Merge', 'Merge', 'Aiguillage', ...
        'Rend celle de ses entrées dont le sous-système vient de calculer', ...
        {'Inputs', 2, N; 'InitialOutput', 0, N}, {}, ...
        {'simulink/Signal Routing/Merge'}, {});
    % --- Simscape : réseaux électriques (Foundation Library) ---
    % Leurs ports physiques, LConn à gauche et RConn à droite, se relient
    % par ADD_LINE ; MATLIBRE_SL_PHYSIQUE met chaque réseau en équations.
    % Un paramètre NOM_unit dit l'unité de NOM.
    cat(end+1) = e('resistor', 'SimscapeBlock', 'Resistor', 'Simscape', ...
        'Résistance : v = R i', {'R', 1, N; 'R_unit', 'Ohm', T}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Resistor'}, {});
    cat(end+1) = e('capacitor', 'SimscapeBlock', 'Capacitor', 'Simscape', ...
        'Condensateur : i = C dv/dt ; résistance série, conductance parallèle', ...
        {'c', 1, N; 'c_unit', 'F', T; 'r', 1e-6, N; 'r_unit', 'Ohm', T; ...
         'g', 0, N; 'g_unit', '1/Ohm', T; 'vc', 0, N; 'vc_unit', 'V', T}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Capacitor'}, {});
    cat(end+1) = e('inductor', 'SimscapeBlock', 'Inductor', 'Simscape', ...
        'Bobine : v = L di/dt ; résistance série, conductance parallèle', ...
        {'l', 1, N; 'l_unit', 'H', T; 'r', 0, N; 'r_unit', 'Ohm', T; ...
         'g', 1e-9, N; 'g_unit', '1/Ohm', T; 'iL', 0, N; 'iL_unit', 'A', T}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Inductor'}, {});
    cat(end+1) = e('electricalreference', 'SimscapeBlock', 'Electrical Reference', ...
        'Simscape', 'La référence des tensions : 0 V', {}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Electrical Reference'}, {});
    cat(end+1) = e('solverconfiguration', 'SimscapeBlock', 'Solver Configuration', ...
        'Simscape', 'Le réglage du réseau physique qu''il touche ; un par réseau', ...
        {'UseLocalSolver', 'off', {'off', 'on'}; 'LocalSolverSampleTime', 0.001, N; ...
         'ConsistencyTolerance', 1e-9, N}, {}, {'nesl_utility/Solver Configuration'}, {});
    cat(end+1) = e('dcvoltagesource', 'SimscapeBlock', 'DC Voltage Source', 'Simscape', ...
        'Source de tension constante : v(+) - v(-) = v0', {'v0', 1, N; 'v0_unit', 'V', T}, ...
        {}, {'fl_lib/Electrical/Electrical Sources/DC Voltage Source'}, {});
    cat(end+1) = e('dccurrentsource', 'SimscapeBlock', 'DC Current Source', 'Simscape', ...
        'Source de courant constante : i0, du + au - à travers la source', ...
        {'i0', 1, N; 'i0_unit', 'A', T}, {}, ...
        {'fl_lib/Electrical/Electrical Sources/DC Current Source'}, {});
    cat(end+1) = e('acvoltagesource', 'SimscapeBlock', 'AC Voltage Source', 'Simscape', ...
        'Source de tension sinusoïdale : amp sin(2 pi f t + shift)', ...
        {'amp', 1, N; 'amp_unit', 'V', T; 'shift', 0, N; 'shift_unit', 'deg', T; ...
         'frequency', 60, N; 'frequency_unit', 'Hz', T}, {}, ...
        {'fl_lib/Electrical/Electrical Sources/AC Voltage Source'}, {});
    cat(end+1) = e('accurrentsource', 'SimscapeBlock', 'AC Current Source', 'Simscape', ...
        'Source de courant sinusoïdale : amp sin(2 pi f t + shift)', ...
        {'amp', 1, N; 'amp_unit', 'A', T; 'shift', 0, N; 'shift_unit', 'deg', T; ...
         'frequency', 60, N; 'frequency_unit', 'Hz', T}, {}, ...
        {'fl_lib/Electrical/Electrical Sources/AC Current Source'}, {});
    cat(end+1) = e('controlledvoltagesource', 'SimscapeBlock', ...
        'Controlled Voltage Source', 'Simscape', ...
        'Source de tension que commande son entrée : v(+) - v(-) = s', {}, {}, ...
        {'fl_lib/Electrical/Electrical Sources/Controlled Voltage Source'}, {});
    cat(end+1) = e('controlledcurrentsource', 'SimscapeBlock', ...
        'Controlled Current Source', 'Simscape', ...
        'Source de courant que commande son entrée : i = s, du + au -', {}, {}, ...
        {'fl_lib/Electrical/Electrical Sources/Controlled Current Source'}, {});
    cat(end+1) = e('voltagesensor', 'SimscapeBlock', 'Voltage Sensor', 'Simscape', ...
        'Mesure v(+) - v(-)', {}, {}, ...
        {'fl_lib/Electrical/Electrical Sensors/Voltage Sensor'}, {});
    cat(end+1) = e('currentsensor', 'SimscapeBlock', 'Current Sensor', 'Simscape', ...
        'Mesure le courant qui la traverse, du + au -', {}, {}, ...
        {'fl_lib/Electrical/Electrical Sensors/Current Sensor'}, {});
    % --- Simscape : mécanique en translation et en rotation ---
    % Une vitesse est une grandeur « à travers », une force ou un couple une
    % grandeur « traversante » ; R à gauche, C à droite.
    cat(end+1) = e('mass', 'SimscapeBlock', 'Mass', 'Simscape', ...
        'Masse : F = m dv/dt, vers la référence', ...
        {'mass', 1, N; 'mass_unit', 'kg', T; 'v', 0, N; 'v_unit', 'm/s', T}, {}, ...
        {'fl_lib/Mechanical/Translational Elements/Mass'}, {});
    cat(end+1) = e('translationalspring', 'SimscapeBlock', 'Translational Spring', ...
        'Simscape', 'Ressort : F = k x', ...
        {'spr_rate', 1000, N; 'spr_rate_unit', 'N/m', T; 'x', 0, N; 'x_unit', 'm', T}, {}, ...
        {'fl_lib/Mechanical/Translational Elements/Translational Spring'}, {});
    cat(end+1) = e('translationaldamper', 'SimscapeBlock', 'Translational Damper', ...
        'Simscape', 'Amortisseur : F = D v', {'D', 100, N; 'D_unit', 'N/(m/s)', T}, {}, ...
        {'fl_lib/Mechanical/Translational Elements/Translational Damper'}, {});
    cat(end+1) = e('mechanicaltranslationalreference', 'SimscapeBlock', ...
        'Mechanical Translational Reference', 'Simscape', 'Le repère fixe : v = 0', {}, {}, ...
        {'fl_lib/Mechanical/Translational Elements/Mechanical Translational Reference'}, {});
    cat(end+1) = e('idealforcesource', 'SimscapeBlock', 'Ideal Force Source', 'Simscape', ...
        'Force que commande son entrée ; positive, elle pousse R', {}, {}, ...
        {'fl_lib/Mechanical/Mechanical Sources/Ideal Force Source'}, {});
    cat(end+1) = e('idealtranslationalvelocitysource', 'SimscapeBlock', ...
        'Ideal Translational Velocity Source', 'Simscape', ...
        'Vitesse que commande son entrée : v(R) - v(C) = s', {}, {}, ...
        {'fl_lib/Mechanical/Mechanical Sources/Ideal Translational Velocity Source'}, {});
    cat(end+1) = e('idealtranslationalmotionsensor', 'SimscapeBlock', ...
        'Ideal Translational Motion Sensor', 'Simscape', ...
        'Mesure la vitesse v(R) - v(C) et la position', {'x0', 0, N; 'x0_unit', 'm', T}, {}, ...
        {'fl_lib/Mechanical/Mechanical Sensors/Ideal Translational Motion Sensor'}, {});
    cat(end+1) = e('idealforcesensor', 'SimscapeBlock', 'Ideal Force Sensor', 'Simscape', ...
        'Mesure la force qui la traverse, de R à C', {}, {}, ...
        {'fl_lib/Mechanical/Mechanical Sensors/Ideal Force Sensor'}, {});
    cat(end+1) = e('inertia', 'SimscapeBlock', 'Inertia', 'Simscape', ...
        'Inertie : T = J dw/dt, vers la référence', ...
        {'inertia', 0.01, N; 'inertia_unit', 'kg*m^2', T; 'w', 0, N; 'w_unit', 'rad/s', T}, ...
        {}, {'fl_lib/Mechanical/Rotational Elements/Inertia'}, {});
    cat(end+1) = e('rotationalspring', 'SimscapeBlock', 'Rotational Spring', 'Simscape', ...
        'Ressort de torsion : T = k phi', ...
        {'spr_rate', 10, N; 'spr_rate_unit', 'N*m/rad', T; 'phi', 0, N; 'phi_unit', 'rad', T}, ...
        {}, {'fl_lib/Mechanical/Rotational Elements/Rotational Spring'}, {});
    cat(end+1) = e('rotationaldamper', 'SimscapeBlock', 'Rotational Damper', 'Simscape', ...
        'Amortisseur de rotation : T = D w', {'D', 0.001, N; 'D_unit', 'N*m/(rad/s)', T}, {}, ...
        {'fl_lib/Mechanical/Rotational Elements/Rotational Damper'}, {});
    cat(end+1) = e('mechanicalrotationalreference', 'SimscapeBlock', ...
        'Mechanical Rotational Reference', 'Simscape', 'Le repère fixe : w = 0', {}, {}, ...
        {'fl_lib/Mechanical/Rotational Elements/Mechanical Rotational Reference'}, {});
    cat(end+1) = e('idealtorquesource', 'SimscapeBlock', 'Ideal Torque Source', 'Simscape', ...
        'Couple que commande son entrée ; positif, il pousse R', {}, {}, ...
        {'fl_lib/Mechanical/Mechanical Sources/Ideal Torque Source'}, {});
    cat(end+1) = e('idealangularvelocitysource', 'SimscapeBlock', ...
        'Ideal Angular Velocity Source', 'Simscape', ...
        'Vitesse angulaire que commande son entrée : w(R) - w(C) = s', {}, {}, ...
        {'fl_lib/Mechanical/Mechanical Sources/Ideal Angular Velocity Source'}, {});
    cat(end+1) = e('idealrotationalmotionsensor', 'SimscapeBlock', ...
        'Ideal Rotational Motion Sensor', 'Simscape', ...
        'Mesure la vitesse angulaire w(R) - w(C) et l''angle', ...
        {'phi0', 0, N; 'phi0_unit', 'rad', T}, {}, ...
        {'fl_lib/Mechanical/Mechanical Sensors/Ideal Rotational Motion Sensor'}, {});
    cat(end+1) = e('idealtorquesensor', 'SimscapeBlock', 'Ideal Torque Sensor', 'Simscape', ...
        'Mesure le couple qui le traverse, de R à C', {}, {}, ...
        {'fl_lib/Mechanical/Mechanical Sensors/Ideal Torque Sensor'}, {});
    cat(end+1) = e('rotationalelectromechanicalconverter', 'SimscapeBlock', ...
        'Rotational Electromechanical Converter', 'Simscape', ...
        'Moteur ou génératrice : v = K w, couple = K i ; + et - à gauche, R et C à droite', ...
        {'K', 0.1, N; 'K_unit', 'V/(rad/s)', T}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Rotational Electromechanical Converter'}, {});
    % --- Simscape : thermique ---
    % Une température (absolue, en kelvins) est une grandeur « à travers », un
    % flux de chaleur une grandeur « traversante » ; A à gauche, B à droite.
    cat(end+1) = e('thermalmass', 'SimscapeBlock', 'Thermal Mass', 'Simscape', ...
        'Masse thermique : Q = m c dT/dt, vers la référence', ...
        {'mass', 1, N; 'mass_unit', 'kg', T; 'sp_heat', 447, N; 'sp_heat_unit', 'J/(kg*K)', T; ...
         'T', 300, N; 'T_unit', 'K', T}, {}, {'fl_lib/Thermal/Thermal Elements/Thermal Mass'}, {});
    cat(end+1) = e('conductiveheattransfer', 'SimscapeBlock', 'Conductive Heat Transfer', ...
        'Simscape', 'Conduction : Q = k S (TA - TB) / e', ...
        {'area', 1e-4, N; 'area_unit', 'm^2', T; 'thickness', 0.1, N; 'thickness_unit', 'm', T; ...
         'th_cond', 401, N; 'th_cond_unit', 'W/(m*K)', T}, {}, ...
        {'fl_lib/Thermal/Thermal Elements/Conductive Heat Transfer'}, {});
    cat(end+1) = e('convectiveheattransfer', 'SimscapeBlock', 'Convective Heat Transfer', ...
        'Simscape', 'Convection : Q = h S (TA - TB)', ...
        {'area', 1e-4, N; 'area_unit', 'm^2', T; 'heat_tr_coeff', 20, N; ...
         'heat_tr_coeff_unit', 'W/(m^2*K)', T}, {}, ...
        {'fl_lib/Thermal/Thermal Elements/Convective Heat Transfer'}, {});
    cat(end+1) = e('thermalreference', 'SimscapeBlock', 'Thermal Reference', 'Simscape', ...
        'Le zéro absolu des températures', {}, {}, ...
        {'fl_lib/Thermal/Thermal Elements/Thermal Reference'}, {});
    cat(end+1) = e('idealtemperaturesource', 'SimscapeBlock', 'Ideal Temperature Source', ...
        'Simscape', 'Température que commande son entrée : T(B) - T(A) = s', {}, {}, ...
        {'fl_lib/Thermal/Thermal Sources/Ideal Temperature Source', ...
         'fl_lib/Thermal/Thermal Sources/Controlled Temperature Source'}, {});
    cat(end+1) = e('idealheatflowsource', 'SimscapeBlock', 'Ideal Heat Flow Source', ...
        'Simscape', 'Flux de chaleur que commande son entrée, de A vers B', {}, {}, ...
        {'fl_lib/Thermal/Thermal Sources/Ideal Heat Flow Source', ...
         'fl_lib/Thermal/Thermal Sources/Controlled Heat Flow Rate Source'}, {});
    cat(end+1) = e('idealtemperaturesensor', 'SimscapeBlock', 'Ideal Temperature Sensor', ...
        'Simscape', 'Mesure T(A) - T(B)', {}, {}, ...
        {'fl_lib/Thermal/Thermal Sensors/Ideal Temperature Sensor', ...
         'fl_lib/Thermal/Thermal Sensors/Temperature Sensor'}, {});
    cat(end+1) = e('idealheatflowsensor', 'SimscapeBlock', 'Ideal Heat Flow Sensor', ...
        'Simscape', 'Mesure le flux de chaleur qui le traverse, de A à B', {}, {}, ...
        {'fl_lib/Thermal/Thermal Sensors/Ideal Heat Flow Sensor', ...
         'fl_lib/Thermal/Thermal Sensors/Heat Flow Rate Sensor'}, {});
    % --- Simscape : électricité, suite ---
    cat(end+1) = e('opamp', 'SimscapeBlock', 'Op-Amp', 'Simscape', ...
        ['Amplificateur opérationnel idéal : v(+) = v(-), sans courant d''entrée ; ' ...
         '+ et - à gauche, la sortie à droite'], {}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Op-Amp'}, {});
    cat(end+1) = e('idealtransformer', 'SimscapeBlock', 'Ideal Transformer', 'Simscape', ...
        'Transformateur idéal : v1 = N v2, i2 = N i1 ; primaire à gauche, secondaire à droite', ...
        {'n', 1, N}, {'WindingRatio', 'n'}, ...
        {'fl_lib/Electrical/Electrical Elements/Ideal Transformer'}, {});
    cat(end+1) = e('mutualinductor', 'SimscapeBlock', 'Mutual Inductor', 'Simscape', ...
        ['Inductances couplées : v1 = L1 di1/dt + M di2/dt, v2 = L2 di2/dt + M di1/dt, ' ...
         'M = k sqrt(L1 L2)'], ...
        {'L1', 10, N; 'L1_unit', 'H', T; 'L2', 0.1, N; 'L2_unit', 'H', T; 'k', 0.9, N; ...
         'i1', 0, N; 'i1_unit', 'A', T; 'i2', 0, N; 'i2_unit', 'A', T}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Mutual Inductor'}, {});
    cat(end+1) = e('voltagecontrolledvoltagesource', 'SimscapeBlock', ...
        'Voltage-Controlled Voltage Source', 'Simscape', ...
        'Tension de sortie K (V(+) - V(-)) ; la commande à gauche, la sortie à droite', ...
        {'K', 1, N}, {}, ...
        {'fl_lib/Electrical/Electrical Sources/Voltage-Controlled Voltage Source'}, {});
    cat(end+1) = e('currentcontrolledvoltagesource', 'SimscapeBlock', ...
        'Current-Controlled Voltage Source', 'Simscape', ...
        'Tension de sortie K I1, I1 allant du + au - de la commande', ...
        {'K', 1, N; 'K_unit', 'Ohm', T}, {}, ...
        {'fl_lib/Electrical/Electrical Sources/Current-Controlled Voltage Source'}, {});
    cat(end+1) = e('opencircuit', 'SimscapeBlock', 'Open Circuit', 'Simscape', ...
        'Un port électrique que rien ne traverse', {}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Open Circuit'}, {});
    cat(end+1) = e('translationalelectromechanicalconverter', 'SimscapeBlock', ...
        'Translational Electromechanical Converter', 'Simscape', ...
        'Moteur linéaire : v = K u, force = K i ; + et - à gauche, R et C à droite', ...
        {'K', 0.1, N; 'K_unit', 'V/(m/s)', T}, {}, ...
        {'fl_lib/Electrical/Electrical Elements/Translational Electromechanical Converter'}, {});
    % --- Simscape : mécanique, suite ---
    cat(end+1) = e('translationalinerter', 'SimscapeBlock', 'Translational Inerter', ...
        'Simscape', 'Inerteur : F = B d(vR - vC)/dt', ...
        {'B', 1, N; 'B_unit', 'kg', T; 'v', 0, N; 'v_unit', 'm/s', T}, {'Inertance', 'B'}, ...
        {'fl_lib/Mechanical/Translational Elements/Translational Inerter'}, {});
    cat(end+1) = e('rotationalinerter', 'SimscapeBlock', 'Rotational Inerter', 'Simscape', ...
        'Inerteur de rotation : T = B d(wR - wC)/dt', ...
        {'B', 1, N; 'B_unit', 'kg*m^2', T; 'w', 0, N; 'w_unit', 'rad/s', T}, ...
        {'Inertance', 'B'}, ...
        {'fl_lib/Mechanical/Rotational Elements/Rotational Inerter'}, {});
    cat(end+1) = e('translationalfreeend', 'SimscapeBlock', 'Translational Free End', ...
        'Simscape', 'Un port de translation libre : aucune force ne s''y exerce', {}, {}, ...
        {'fl_lib/Mechanical/Translational Elements/Translational Free End'}, {});
    cat(end+1) = e('rotationalfreeend', 'SimscapeBlock', 'Rotational Free End', ...
        'Simscape', 'Un port de rotation libre : aucun couple ne s''y exerce', {}, {}, ...
        {'fl_lib/Mechanical/Rotational Elements/Rotational Free End'}, {});
    cat(end+1) = e('gearbox', 'SimscapeBlock', 'Gear Box', 'Simscape', ...
        ['Réducteur idéal : w(S) = N w(O), le couple de sortie N fois celui d''entrée ; ' ...
         'S à gauche, O à droite'], {'ratio', 5, N}, {'GearRatio', 'ratio'}, ...
        {'fl_lib/Mechanical/Mechanisms/Gear Box'}, {});
    cat(end+1) = e('wheelandaxle', 'SimscapeBlock', 'Wheel and Axle', 'Simscape', ...
        'Roue et essieu : v(P) = r w(A) ; l''essieu A à gauche, la périphérie P à droite', ...
        {'radius', 0.05, N; 'radius_unit', 'm', T; ...
         'orientation', 'Drives in positive direction', ...
         {'Drives in positive direction', 'Drives in negative direction'}}, ...
        {'WheelRadius', 'radius'}, {'fl_lib/Mechanical/Mechanisms/Wheel and Axle'}, {});
    cat(end+1) = e('perfectinsulator', 'SimscapeBlock', 'Perfect Insulator', 'Simscape', ...
        'Une paroi parfaitement isolante : aucun flux de chaleur', {}, {}, ...
        {'fl_lib/Thermal/Thermal Elements/Perfect Insulator'}, {});
    % --- Simscape : les signaux physiques ---
    % Un signal physique est un signal en unités SI : ces blocs deviennent,
    % avant la compilation, le bloc de Simulink qui calcule la même chose.
    fonctions = 'fl_lib/Physical Signals/Functions/';
    simples = {'psabs', 'PS Abs', 'Valeur absolue d''un signal physique'
               'pssign', 'PS Sign', 'Le signe d''un signal physique : -1, 0 ou 1'
               'psceil', 'PS Ceil', 'Arrondi vers plus l''infini'
               'psfloor', 'PS Floor', 'Arrondi vers moins l''infini'
               'psround', 'PS Round', 'Arrondi à l''entier le plus proche'
               'psfix', 'PS Fix', 'Arrondi vers zéro'
               'psadd', 'PS Add', 'La somme de deux signaux physiques'
               'pssubtract', 'PS Subtract', 'La différence I1 - I2'
               'psproduct', 'PS Product', 'Le produit de deux signaux physiques'
               'psdivide', 'PS Divide', 'Le quotient I1 / I2'
               'psmax', 'PS Max', 'Le plus grand de deux signaux physiques'
               'psmin', 'PS Min', 'Le plus petit de deux signaux physiques'};
    for k = 1:size(simples, 1)
        cat(end+1) = e(simples{k, 1}, 'SimscapeBlock', simples{k, 2}, 'Simscape', ...
                       simples{k, 3}, {}, {}, {[fonctions simples{k, 2}]}, {}); %#ok<AGROW>
    end
    cat(end+1) = e('psgain', 'SimscapeBlock', 'PS Gain', 'Simscape', ...
        'Multiplie un signal physique par un gain', {'Gain', 1, N; 'Gain_unit', '1', T}, ...
        {}, {[fonctions 'PS Gain']}, {});
    cat(end+1) = e('psmathfunction', 'SimscapeBlock', 'PS Math Function', 'Simscape', ...
        'Une fonction d''un signal physique : sinus, exponentielle, racine, puissance...', ...
        {'Function', 'sin(u)', {'sin(u)', 'cos(u)', 'exp(u)', 'log(u)', '10.^u', ...
                                'log10(u)', 'u.^2', 'sqrt(u)', '1./u', 'tanh(u)', 'u.^v'}; ...
         'v', 1, N}, {'FunctionChoice', 'Function'}, {[fonctions 'PS Math Function']}, {});
    cat(end+1) = e('psconstant', 'SimscapeBlock', 'PS Constant', 'Simscape', ...
        'Un signal physique constant', {'Constant', 1, N; 'Constant_unit', '1', T}, {}, ...
        {'fl_lib/Physical Signals/Sources/PS Constant'}, {});
    cat(end+1) = e('psintegrator', 'SimscapeBlock', 'PS Integrator', 'Simscape', ...
        'Intègre un signal physique : remise, condition initiale externe, bornes', ...
        {'InitialCondition', 0, N; 'InitialCondition_unit', '1', T; ...
         'ExternalReset', 'None', {'None', 'Rising', 'Falling', 'Either'}; ...
         'InitialConditionSource', 'Internal', {'Internal', 'External'}; ...
         'LimitOutput', 'None', {'None', 'Upper', 'Lower', 'Both'}; ...
         'LimitOutputSource', 'Internal', {'Internal', 'External'}; ...
         'UpperLimit', Inf, N; 'UpperLimit_unit', '1', T; ...
         'LowerLimit', -Inf, N; 'LowerLimit_unit', '1', T}, {'x0', 'InitialCondition'}, ...
        {'fl_lib/Physical Signals/Linear Operators/PS Integrator'}, {});
    cat(end+1) = e('pssaturation', 'SimscapeBlock', 'PS Saturation', 'Simscape', ...
        'Borne un signal physique', ...
        {'UpperLimit', 0.5, N; 'UpperLimit_unit', '1', T; 'LowerLimit', -0.5, N; ...
         'LowerLimit_unit', '1', T; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'fl_lib/Physical Signals/Nonlinear Operators/PS Saturation'}, {});
    cat(end+1) = e('psdeadzone', 'SimscapeBlock', 'PS Dead Zone', 'Simscape', ...
        'Annule un signal physique entre deux bornes, et les lui retire au-delà', ...
        {'UpperLimit', 0.5, N; 'UpperLimit_unit', '1', T; 'LowerLimit', -0.5, N; ...
         'LowerLimit_unit', '1', T; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'fl_lib/Physical Signals/Nonlinear Operators/PS Dead Zone'}, {});
    cat(end+1) = e('psswitch', 'SimscapeBlock', 'PS Switch', 'Simscape', ...
        'I1 quand la commande I2 atteint le seuil, I3 sinon', ...
        {'Threshold', 0.5, N; 'Threshold_unit', '1', T; 'ZeroCross', 'on', {'on', 'off'}}, ...
        {}, {'fl_lib/Physical Signals/Nonlinear Operators/PS Switch'}, {});
    cat(end+1) = e('psconstantdelay', 'SimscapeBlock', 'PS Constant Delay', 'Simscape', ...
        'Retarde un signal physique d''une durée ; l''historique d''entrée avant', ...
        {'DelayTime', 1, N; 'DelayTime_unit', 's', T; 'InputHistory', 0, N; ...
         'InputHistory_unit', '1', T}, {}, ...
        {'fl_lib/Physical Signals/Delays/PS Constant Delay'}, {});
    tables = {'Linear', 'Smooth'};
    bords = {'Linear', 'Nearest', 'Error'};
    cat(end+1) = e('pslookuptable1d', 'SimscapeBlock', 'PS Lookup Table (1D)', 'Simscape', ...
        'Une table d''une dimension : linéaire ou lisse (Akima modifié)', ...
        {'x', [1 2 3 4 5], N; 'x_unit', '1', T; 'f', [0 1 2 3 4], N; 'f_unit', '1', T; ...
         'InterpolationMethod', 'Linear', tables; 'ExtrapolationMethod', 'Linear', bords}, ...
        {}, {'fl_lib/Physical Signals/Lookup Tables/PS Lookup Table (1D)'}, {});
    cat(end+1) = e('pslookuptable2d', 'SimscapeBlock', 'PS Lookup Table (2D)', 'Simscape', ...
        'Une table de deux dimensions, f(x1, x2) : linéaire ou lisse', ...
        {'x1', [1 2 3], N; 'x1_unit', '1', T; 'x2', [1 2 3 4], N; 'x2_unit', '1', T; ...
         'f', reshape(1:12, 3, 4), N; 'f_unit', '1', T; ...
         'InterpolationMethod', 'Linear', tables; 'ExtrapolationMethod', 'Linear', bords}, ...
        {}, {'fl_lib/Physical Signals/Lookup Tables/PS Lookup Table (2D)'}, {});
    cat(end+1) = e('psterminator', 'SimscapeBlock', 'PS Terminator', 'Simscape', ...
        'Ferme un signal physique qu''on ne lit pas', {}, {}, ...
        {'fl_lib/Physical Signals/Sinks/PS Terminator'}, {});
    % --- Simscape : les convertisseurs ---
    cat(end+1) = e('simulinkpsconverter', 'SimscapeBlock', 'Simulink-PS Converter', ...
        'Simscape', ['Un signal de Simulink devenu signal physique, dans son unité, ' ...
                     'filtré s''il le faut'], ...
        {'InputSignalUnit', '1', T; 'ApplyAffineConversion', 'off', {'on', 'off'}; ...
         'FilteringAndDerivatives', 'Provide signals', ...
         {'Provide signals', 'Filter input, derivatives calculated', ...
          'Zero derivatives (piecewise constant)'}; ...
         'ProvidedSignals', 'Input only', ...
         {'Input only', 'Input and first derivative', 'Input and first two derivatives'}; ...
         'SimscapeFilterOrder', 'First-order filtering', ...
         {'First-order filtering', 'Second-order filtering'}; ...
         'InputFilterTimeConstant', 0.001, N; 'InputFilterTimeConstant_unit', 's', T}, ...
        {'Unit', 'InputSignalUnit'}, {'nesl_utility/Simulink-PS Converter'}, {});
    cat(end+1) = e('pssimulinkconverter', 'SimscapeBlock', 'PS-Simulink Converter', ...
        'Simscape', 'Un signal physique devenu signal de Simulink, dans l''unité demandée', ...
        {'OutputSignalUnit', '1', T; 'ApplyAffineConversion', 'off', {'on', 'off'}}, ...
        {'Unit', 'OutputSignalUnit'}, {'nesl_utility/PS-Simulink Converter'}, {});

    % La garde : ce que devient le port de contrôle d'un sous-système
    % déplié. Elle n'est pas dans la bibliothèque.
    cat(end+1) = e('garde', 'MatLibreGarde', 'Garde', 'Interne', ...
        'Interne : la condition d''un sous-système conditionnel déplié', ...
        {'Enable', 0, N; 'Trigger', 'none', {'none', 'rising', 'falling', 'either', ...
                                              'function-call'}; ...
         'Action', 0, N; 'Reset', 0, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, {}, {});
end

function x = e(type, simulink, affiche, famille, description, params, alias, ...
               chemins, aliasTypes)
    x = struct('type', type, 'simulink', simulink, 'affiche', affiche, ...
               'famille', famille, 'description', description, ...
               'params', {params}, 'alias', {alias}, 'chemins', {chemins}, ...
               'aliasTypes', {aliasTypes});
end

% Les réglages que tout bloc accepte : ils disent où il est et comment il
% se montre, rien de ce qu'il calcule.
function noms = parametresCommuns()
    noms = {'Position', 'Orientation', 'ForegroundColor', 'BackgroundColor', ...
            'ShowName', 'Description', 'Tag', 'Priority', 'NamePlacement', ...
            'FontSize', 'FontName', 'DropShadow', 'AttributesFormatString', ...
            'UserData'};
end

% --- les recherches ---------------------------------------------------------

function index = indexer(cat)
    index = containers.Map();
    for k = 1:numel(cat)
        cles = [{cat(k).type, cat(k).simulink, cat(k).affiche}, cat(k).chemins, ...
                cat(k).aliasTypes];
        for j = 1:numel(cles)
            cle = normaliser(cles{j});
            if ~isKey(index, cle)
                index(cle) = k;
            end
        end
    end
end

% Une désignation se compare sans la casse ni les espaces : « Sine Wave »,
% « sinewave » et « SineWave » désignent le même bloc.
function cle = normaliser(texte)
    cle = lower(regexprep(char(texte), '\s', ''));
end

function x = resoudreType(cat, index, designation)
    if isstruct(designation)
        x = designation;
        return
    end
    brut = char(designation);
    cle = normaliser(brut);
    if isKey(index, cle)
        x = cat(index(cle));
        return
    end
    % Un chemin de bibliothèque qu'on ne connaît pas en entier : son
    % dernier segment est le nom du bloc.
    barre = find(brut == '/', 1, 'last');
    if ~isempty(barre)
        dernier = normaliser(brut(barre + 1:end));
        if isKey(index, dernier)
            x = cat(index(dernier));
            return
        end
    end
    error('Simulink:Commands:InvalidBlockType', ...
          ['Le type de bloc ''%s'' est inconnu. Les types reconnus sont ceux ' ...
           'qu''ADD_BLOCK decrit ; ils se designent aussi par leur nom Simulink ' ...
           '(''Gain'', ''Sine Wave'') ou leur chemin de bibliotheque ' ...
           '(''simulink/Math Operations/Gain'').'], brut);
end

function nom = resoudreParametre(x, demande)
    nom = '';
    demande = char(demande);
    for k = 1:size(x.params, 1)
        if strcmpi(x.params{k, 1}, demande)
            nom = x.params{k, 1};
            return
        end
    end
    for k = 1:size(x.alias, 1)
        if strcmpi(x.alias{k, 1}, demande)
            nom = x.alias{k, 2};
            return
        end
    end
    communs = parametresCommuns();
    for k = 1:numel(communs)
        if strcmpi(communs{k}, demande)
            nom = communs{k};
            return
        end
    end
end
