function varargout = matlibre_sl_catalogue(action, varargin)
%MATLIBRE_SL_CATALOGUE Le catalogue des blocs : types, paramètres, bibliothèque.
%   CAT = MATLIBRE_SL_CATALOGUE() rend le tableau de structures qui décrit
%   chaque type de bloc que SIM sait simuler : son nom dans MatLibre, son
%   type Simulink (BlockType), son nom dans la bibliothèque de Simulink et
%   ses chemins (« simulink/Math Operations/Gain »), sa famille dans la
%   bibliothèque du bureau, et la liste de ses paramètres avec leur valeur
%   par défaut et leur nature.
%
%   E = MATLIBRE_SL_CATALOGUE('type',DESIGNATION) rend l'entrée d'un type,
%   désigné par son nom MatLibre (« gain »), son type Simulink (« Gain »,
%   « Sin », « Saturate »), son nom de bibliothèque (« Sine Wave »,
%   « Zero-Order Hold ») ou son chemin (« simulink/Sources/Step »). Une
%   désignation inconnue est refusée en disant les types voisins.
%
%   NOM = MATLIBRE_SL_CATALOGUE('parametre',E,NOM) rend l'écriture
%   canonique d'un nom de paramètre pour le type E — la casse est
%   indifférente, comme dans Simulink, et les noms de Simulink et ceux de
%   MatLibre sont reconnus l'un pour l'autre (« Inputs » et « Signs » pour
%   une sommation). Rend '' si le type ne porte pas ce paramètre.
%
%   C'est la source unique de ce que chaque bloc accepte : ADD_BLOCK et
%   SET_PARAM y valident les paramètres, GET_PARAM y lit les valeurs par
%   défaut, SIM y prend les défauts qu'on n'a pas écrits.
%
%   Fonction interne à la boîte à outils : elle n'existe pas dans MATLAB.
%
%   Exemple :
%      e = matlibre_sl_catalogue('type', 'simulink/Math Operations/Gain');
%      e.type                                        % 'gain'
%      matlibre_sl_catalogue('parametre', e, 'gain') % 'Gain'
%
%   Voir aussi ADD_BLOCK, SET_PARAM, GET_PARAM, SIM.
    persistent catalogue index
    if isempty(catalogue)
        catalogue = construire();
        index = indexer(catalogue);
    end
    if nargin == 0
        varargout{1} = catalogue;
        return
    end
    switch lower(char(action))
        case 'type'
            varargout{1} = resoudreType(catalogue, index, varargin{1});
        case 'parametre'
            varargout{1} = resoudreParametre(varargin{1}, varargin{2});
        case 'communs'
            varargout{1} = parametresCommuns();
        otherwise
            error('Simulink:Catalogue:Action', 'Action inconnue : %s.', char(action));
    end
end

% --- les entrées ------------------------------------------------------------
%
% Chaque paramètre est un triplet {nom, défaut, nature}. La nature vaut
% 'nombre' (une valeur ou une expression évaluée dans l'espace de travail
% au moment de simuler), 'texte' (une chaîne lue telle quelle), 'modele'
% (un modèle entier), 'libre' (rangé sans contrôle), ou une liste de choix.
% Un défaut vide pour une période d'échantillonnage veut dire : celle que
% MatLibre prend quand on ne dit rien, et que l'aide du bloc précise.
function cat = construire()
    cat = struct('type', {}, 'simulink', {}, 'affiche', {}, 'famille', {}, ...
                 'description', {}, 'params', {}, 'alias', {}, 'chemins', {}, ...
                 'aliasTypes', {});
    N = 'nombre';
    T = 'texte';

    % --- Sources ---
    cat(end+1) = e('constant', 'Constant', 'Constant', 'Sources', ...
        'Une valeur constante, scalaire, vecteur ou matrice', ...
        {'Value', 1, N; 'SampleTime', Inf, N}, {}, ...
        {'simulink/Sources/Constant', 'simulink/Commonly Used Blocks/Constant'}, {});
    cat(end+1) = e('step', 'Step', 'Step', 'Sources', ...
        'Un échelon à l''instant dit', ...
        {'Time', 1, N; 'Before', 0, N; 'After', 1, N; 'SampleTime', 0, N; ...
         'ZeroCross', 'on', {'on', 'off'}}, ...
        {'InitialValue', 'Before'; 'FinalValue', 'After'}, ...
        {'simulink/Sources/Step'}, {});
    cat(end+1) = e('ramp', 'Ramp', 'Ramp', 'Sources', ...
        'Une rampe de pente donnée, à partir d''un instant', ...
        {'Slope', 1, N; 'Start', 0, N; 'InitialOutput', 0, N}, {'X0', 'InitialOutput'}, ...
        {'simulink/Sources/Ramp'}, {});
    cat(end+1) = e('sine', 'Sin', 'Sine Wave', 'Sources', ...
        'Une sinusoïde', ...
        {'Amplitude', 1, N; 'Frequency', 1, N; 'Phase', 0, N; 'Bias', 0, N; ...
         'SampleTime', 0, N}, {}, ...
        {'simulink/Sources/Sine Wave'}, {'sin', 'sinewave'});
    cat(end+1) = e('clock', 'Clock', 'Clock', 'Sources', ...
        'Le temps de la simulation', ...
        {'DisplayTime', 'off', {'on', 'off'}; 'Decimation', 10, N}, {}, ...
        {'simulink/Sources/Clock'}, {});
    cat(end+1) = e('digitalclock', 'DigitalClock', 'Digital Clock', 'Sources', ...
        'Le temps, tenu entre deux instants d''échantillonnage', ...
        {'SampleTime', 1, N}, {}, {'simulink/Sources/Digital Clock'}, {});
    cat(end+1) = e('pulsegenerator', 'DiscretePulseGenerator', 'Pulse Generator', ...
        'Sources', 'Un train d''impulsions rectangulaires', ...
        {'Amplitude', 1, N; 'Period', 10, N; 'PulseWidth', 5, N; 'PhaseDelay', 0, N; ...
         'PulseType', 'Time based', {'Time based', 'Sample based'}; ...
         'SampleTime', 1, N}, {}, ...
        {'simulink/Sources/Pulse Generator'}, {'pulse'});
    cat(end+1) = e('ground', 'Ground', 'Ground', 'Sources', ...
        'Un zéro, pour une entrée qu''on ne veut pas laisser en l''air', ...
        {}, {}, {'simulink/Sources/Ground', 'simulink/Commonly Used Blocks/Ground'}, {});
    cat(end+1) = e('repeatingsequence', 'RepeatingSequence', 'Repeating Sequence', ...
        'Sources', 'Une séquence périodique, interpolée entre ses points', ...
        {'rep_seq_t', [0 2], N; 'rep_seq_y', [0 2], N}, ...
        {'TimeValues', 'rep_seq_t'; 'OutputValues', 'rep_seq_y'}, ...
        {'simulink/Sources/Repeating Sequence'}, {});
    cat(end+1) = e('randomnumber', 'RandomNumber', 'Random Number', 'Sources', ...
        'Un bruit gaussien, reproductible par sa graine', ...
        {'Mean', 0, N; 'Variance', 1, N; 'Seed', 0, N; 'SampleTime', 0.1, N}, {}, ...
        {'simulink/Sources/Random Number'}, {});
    cat(end+1) = e('uniformrandomnumber', 'UniformRandomNumber', ...
        'Uniform Random Number', 'Sources', ...
        'Un bruit uniforme, reproductible par sa graine', ...
        {'Minimum', -1, N; 'Maximum', 1, N; 'Seed', 0, N; 'SampleTime', 0.1, N}, {}, ...
        {'simulink/Sources/Uniform Random Number'}, {});
    cat(end+1) = e('inport', 'Inport', 'In1', 'Sources', ...
        'L''entrée du modèle, vue par LINMOD', ...
        {'Port', 1, N; 'Value', 0, N; 'PortDimensions', -1, N}, {}, ...
        {'simulink/Sources/In1', 'simulink/Ports & Subsystems/In1', ...
         'simulink/Commonly Used Blocks/In1'}, {'in1', 'in'});
    cat(end+1) = e('fromworkspace', 'FromWorkspace', 'From Workspace', 'Sources', ...
        'Un signal lu dans l''espace de travail', ...
        {'VariableName', '', T; 'Interpolate', 'on', {'on', 'off'}; ...
         'OutputAfterFinalValue', 'Holding final value', ...
         {'Extrapolation', 'Setting to zero', 'Holding final value'}; ...
         'SampleTime', 0, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Sources/From Workspace'}, {});

    % --- Opérations ---
    cat(end+1) = e('gain', 'Gain', 'Gain', 'Opérations', ...
        'Multiplie par un gain, terme à terme ou matriciel', ...
        {'Gain', 1, N; 'Multiplication', 'Element-wise(K.*u)', ...
         {'Element-wise(K.*u)', 'Matrix(K*u)', 'Matrix(u*K)', 'Matrix(K*u) (u vector)'}; ...
         'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Gain', 'simulink/Commonly Used Blocks/Gain'}, ...
        {'slidergain'});
    cat(end+1) = e('sum', 'Sum', 'Sum', 'Opérations', ...
        'Somme ses entrées selon leurs signes ; une seule entrée : somme de ses éléments', ...
        {'Signs', '++', T; 'IconShape', 'rectangular', 'libre'; 'SampleTime', -1, N}, ...
        {'Inputs', 'Signs'; 'ListOfSigns', 'Signs'}, ...
        {'simulink/Math Operations/Sum', 'simulink/Math Operations/Add', ...
         'simulink/Math Operations/Subtract', 'simulink/Math Operations/Sum of Elements', ...
         'simulink/Commonly Used Blocks/Sum'}, {'add', 'subtract', 'sumofelements'});
    cat(end+1) = e('product', 'Product', 'Product', 'Opérations', ...
        'Multiplie ou divise ses entrées ; une seule entrée : produit de ses éléments', ...
        {'Inputs', '**', T; 'Multiplication', 'Element-wise(.*)', ...
         {'Element-wise(.*)', 'Matrix(*)'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Product', 'simulink/Math Operations/Divide', ...
         'simulink/Math Operations/Product of Elements', ...
         'simulink/Commonly Used Blocks/Product'}, {'divide', 'productofelements'});
    cat(end+1) = e('abs', 'Abs', 'Abs', 'Opérations', 'Valeur absolue', ...
        {'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Math Operations/Abs'}, {});
    cat(end+1) = e('sign', 'Signum', 'Sign', 'Opérations', 'Le signe : -1, 0 ou 1', ...
        {'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Math Operations/Sign'}, {'signum'});
    cat(end+1) = e('math', 'Math', 'Math Function', 'Opérations', ...
        'Carré, racine, exponentielle, logarithme, puissance, modulo...', ...
        {'Operator', 'square', {'exp', 'log', '10^u', 'log10', 'magnitude^2', ...
         'square', 'sqrt', 'pow', 'conj', 'reciprocal', 'hypot', 'rem', 'mod', ...
         'transpose', 'hermitian'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Math Function'}, {'mathfunction'});
    cat(end+1) = e('trigonometry', 'Trigonometry', 'Trigonometric Function', ...
        'Opérations', 'Sinus, cosinus, tangente, leurs réciproques et hyperboliques', ...
        {'Operator', 'sin', {'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2', ...
         'sinh', 'cosh', 'tanh', 'asinh', 'acosh', 'atanh', 'sincos'}; ...
         'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Trigonometric Function'}, ...
        {'trigonometricfunction'});
    cat(end+1) = e('minmax', 'MinMax', 'MinMax', 'Opérations', ...
        'Le plus petit ou le plus grand ; une seule entrée : sur ses éléments', ...
        {'Function', 'min', {'min', 'max'}; 'Inputs', 2, N; 'SampleTime', -1, N; ...
         'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Math Operations/MinMax'}, {});
    cat(end+1) = e('datatypeconversion', 'DataTypeConversion', 'Data Type Conversion', ...
        'Opérations', 'Convertit le signal dans un type : entier, simple précision, booléen', ...
        {'OutDataTypeStr', 'Inherit: Inherit via back propagation', ...
         {'Inherit: Inherit via back propagation', 'double', 'single', 'int8', 'uint8', ...
          'int16', 'uint16', 'int32', 'uint32', 'boolean'}; ...
         'RndMeth', 'Zero', {'Zero', 'Nearest', 'Round', 'Floor', 'Ceiling', 'Convergent', ...
                             'Simplest'}; ...
         'SaturateOnIntegerOverflow', 'off', {'off', 'on'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Signal Attributes/Data Type Conversion', ...
         'simulink/Commonly Used Blocks/Data Type Conversion'}, {});
    cat(end+1) = e('bias', 'Bias', 'Bias', 'Opérations', 'Ajoute une constante', ...
        {'Bias', 0, N; 'SampleTime', -1, N}, {}, {'simulink/Math Operations/Bias'}, {});
    cat(end+1) = e('dotproduct', 'DotProduct', 'Dot Product', 'Opérations', ...
        'Le produit scalaire de ses deux entrées', ...
        {'SampleTime', -1, N}, {}, {'simulink/Math Operations/Dot Product'}, {});
    cat(end+1) = e('unaryminus', 'UnaryMinus', 'Unary Minus', 'Opérations', ...
        'L''opposé', {'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Unary Minus'}, {});
    cat(end+1) = e('rounding', 'Rounding', 'Rounding Function', 'Opérations', ...
        'Arrondit : floor, ceil, round ou fix', ...
        {'Operator', 'floor', {'floor', 'ceil', 'round', 'fix'}; 'SampleTime', -1, N}, ...
        {}, {'simulink/Math Operations/Rounding Function'}, {'roundingfunction'});
    cat(end+1) = e('polynomial', 'Polyval', 'Polynomial', 'Opérations', ...
        'Évalue un polynôme en son entrée', ...
        {'coefs', [1 0], N; 'SampleTime', -1, N}, {'Coefs', 'coefs'}, ...
        {'simulink/Math Operations/Polynomial'}, {'polyval'});
    cat(end+1) = e('sqrt', 'Sqrt', 'Sqrt', 'Opérations', ...
        'Racine carrée ; son inverse ; ou racine du module avec le signe', ...
        {'Operator', 'sqrt', {'sqrt', 'signedSqrt', 'rSqrt'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Math Operations/Sqrt'}, {});

    % --- Non-linéarités ---
    cat(end+1) = e('saturation', 'Saturate', 'Saturation', 'Non-linéarités', ...
        'Borne le signal', ...
        {'UpperLimit', 1, N; 'LowerLimit', -1, N; 'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Discontinuities/Saturation', ...
         'simulink/Commonly Used Blocks/Saturation'}, {'saturate'});
    cat(end+1) = e('deadzone', 'DeadZone', 'Dead Zone', 'Non-linéarités', ...
        'Annule une bande autour de zéro', ...
        {'UpperValue', 0.5, N; 'LowerValue', -0.5, N; 'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, ...
        {'Start', 'LowerValue'; 'End', 'UpperValue'}, ...
        {'simulink/Discontinuities/Dead Zone'}, {});
    cat(end+1) = e('relay', 'Relay', 'Relay', 'Non-linéarités', ...
        'Bascule à deux seuils', ...
        {'OnSwitch', 0.5, N; 'OffSwitch', -0.5, N; 'OnOutput', 1, N; ...
         'OffOutput', 0, N; 'ZeroCross', 'on', {'on', 'off'}}, ...
        {'OnSwitchValue', 'OnSwitch'; 'OffSwitchValue', 'OffSwitch'; ...
         'OnOutputValue', 'OnOutput'; 'OffOutputValue', 'OffOutput'}, ...
        {'simulink/Discontinuities/Relay'}, {});
    cat(end+1) = e('quantizer', 'Quantizer', 'Quantizer', 'Non-linéarités', ...
        'Arrondit à un pas donné', ...
        {'QuantizationInterval', 0.5, N; 'SampleTime', -1, N}, {}, ...
        {'simulink/Discontinuities/Quantizer'}, {});
    cat(end+1) = e('ratelimiter', 'RateLimiter', 'Rate Limiter', 'Non-linéarités', ...
        'Borne la pente du signal', ...
        {'RisingSlewLimit', 1, N; 'FallingSlewLimit', -1, N; 'InitialOutput', 0, N}, ...
        {'RisingSlewRate', 'RisingSlewLimit'; 'FallingSlewRate', 'FallingSlewLimit'}, ...
        {'simulink/Discontinuities/Rate Limiter'}, {});
    cat(end+1) = e('hitcrossing', 'HitCross', 'Hit Crossing', 'Non-linéarités', ...
        'Vaut 1 à l''instant où l''entrée franchit un seuil', ...
        {'HitCrossingOffset', 0, N; 'HitCrossingDirection', 'either', ...
         {'rising', 'falling', 'either'}; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Discontinuities/Hit Crossing'}, {'hitcross'});
    cat(end+1) = e('backlash', 'Backlash', 'Backlash', 'Non-linéarités', ...
        'Un jeu mécanique : la sortie ne suit qu''au-delà d''une largeur', ...
        {'BacklashWidth', 1, N; 'InitialOutput', 0, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Discontinuities/Backlash'}, {});
    cat(end+1) = e('coulombfriction', 'CoulombViscousFriction', ...
        'Coulomb & Viscous Friction', 'Non-linéarités', ...
        'Frottement sec et visqueux : signe(u) (offset + gain |u|)', ...
        {'offset', 1, N; 'gain', 1, N; 'ZeroCross', 'on', {'on', 'off'}}, {'Offset', 'offset'; 'Gain', 'gain'}, ...
        {'simulink/Discontinuities/Coulomb & Viscous Friction'}, ...
        {'coulombviscousfriction'});
    cat(end+1) = e('lookup', 'Lookup_n-D', '1-D Lookup Table', 'Non-linéarités', ...
        'Interpole dans une table ; hors des bornes, tenue ou prolongée', ...
        {'BreakpointsData', [0 1], N; 'TableData', [0 1], N; ...
         'InterpMethod', 'Linear point-slope', {'Linear point-slope', 'Linear', ...
         'Flat', 'Nearest'}; 'ExtrapMethod', 'Clip', {'Clip', 'Linear'}; ...
         'SampleTime', -1, N}, ...
        {'BreakpointsForDimension1', 'BreakpointsData'; 'Table', 'TableData'}, ...
        {'simulink/Lookup Tables/1-D Lookup Table'}, ...
        {'lookup_n-d', 'lookuptable', '1-dlookuptable'});
    cat(end+1) = e('lookup2d', 'Lookup2D', '2-D Lookup Table', 'Non-linéarités', ...
        'Interpole dans une table à deux entrées', ...
        {'BreakpointsForDimension1', [0 1], N; 'BreakpointsForDimension2', [0 1], N; ...
         'Table', [0 0; 0 1], N; 'SampleTime', -1, N}, ...
        {'RowIndex', 'BreakpointsForDimension1'; ...
         'ColumnIndex', 'BreakpointsForDimension2'; 'OutputValues', 'Table'}, ...
        {'simulink/Lookup Tables/2-D Lookup Table'}, {'2-dlookuptable'});

    % --- Logique ---
    cat(end+1) = e('logic', 'Logic', 'Logical Operator', 'Logique', ...
        'ET, OU, NON, OU exclusif ; une seule entrée : sur ses éléments', ...
        {'Operator', 'AND', {'AND', 'OR', 'NAND', 'NOR', 'XOR', 'NXOR', 'NOT'}; ...
         'Inputs', 2, N; 'SampleTime', -1, N}, {}, ...
        {'simulink/Logic and Bit Operations/Logical Operator', ...
         'simulink/Commonly Used Blocks/Logical Operator'}, {'logicaloperator'});
    cat(end+1) = e('relational', 'RelationalOperator', 'Relational Operator', ...
        'Logique', 'Compare deux entrées', ...
        {'Operator', '<', {'==', '~=', '<', '<=', '>=', '>'}; 'SampleTime', -1, N; ...
         'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Logic and Bit Operations/Relational Operator', ...
         'simulink/Commonly Used Blocks/Relational Operator'}, ...
        {'relationaloperator'});
    cat(end+1) = e('comparetoconstant', 'CompareToConstant', 'Compare To Constant', ...
        'Logique', 'Compare l''entrée à une constante', ...
        {'relop', '<=', {'==', '~=', '<', '<=', '>=', '>'}; 'const', 3, N; 'ZeroCross', 'on', {'on', 'off'}}, ...
        {'Operator', 'relop'; 'Constant', 'const'}, ...
        {'simulink/Logic and Bit Operations/Compare To Constant'}, {});
    cat(end+1) = e('comparetozero', 'CompareToZero', 'Compare To Zero', 'Logique', ...
        'Compare l''entrée à zéro', ...
        {'relop', '<=', {'==', '~=', '<', '<=', '>=', '>'}; 'ZeroCross', 'on', {'on', 'off'}}, ...
        {'Operator', 'relop'}, ...
        {'simulink/Logic and Bit Operations/Compare To Zero'}, {});
    cat(end+1) = e('detectchange', 'DetectChange', 'Detect Change', 'Logique', ...
        'Vaut 1 quand l''entrée diffère de celle du pas précédent', ...
        {'vinit', 0, N}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Change'}, {});
    cat(end+1) = e('detectincrease', 'DetectIncrease', 'Detect Increase', 'Logique', ...
        'Vaut 1 quand l''entrée a augmenté depuis le pas précédent', ...
        {'vinit', 0, N}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Increase'}, {});
    cat(end+1) = e('detectdecrease', 'DetectDecrease', 'Detect Decrease', 'Logique', ...
        'Vaut 1 quand l''entrée a diminué depuis le pas précédent', ...
        {'vinit', 0, N}, {'InitialCondition', 'vinit'}, ...
        {'simulink/Logic and Bit Operations/Detect Decrease'}, {});

    % --- Aiguillage ---
    cat(end+1) = e('switch', 'Switch', 'Switch', 'Aiguillage', ...
        'Aiguille selon un seuil sur la deuxième entrée', ...
        {'Threshold', 0, N; 'Criteria', 'u2 >= Threshold', ...
         {'u2 >= Threshold', 'u2 > Threshold', 'u2 ~= 0'}; 'SampleTime', -1, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Signal Routing/Switch', 'simulink/Commonly Used Blocks/Switch'}, {});
    cat(end+1) = e('multiportswitch', 'MultiPortSwitch', 'Multiport Switch', ...
        'Aiguillage', 'La première entrée choisit laquelle des suivantes passe', ...
        {'Inputs', 3, N; 'DataPortOrder', 'One-based contiguous', ...
         {'One-based contiguous', 'Zero-based contiguous'}; 'SampleTime', -1, N}, {}, ...
        {'simulink/Signal Routing/Multiport Switch'}, {});
    % Un bus : des signaux réunis sous leurs noms, qu'un Bus Selector
    % reprend par ces noms — « vitesse », ou « mesures.vitesse » dans un
    % bus emboîté. Inputs vaut un nombre (les éléments s'appellent alors
    % signal1, signal2...) ou la liste des noms, « vitesse,position ».
    cat(end+1) = e('buscreator', 'BusCreator', 'Bus Creator', 'Aiguillage', ...
        'Réunit ses entrées en un bus, chaque élément sous son nom', ...
        {'Inputs', '2', T}, {}, ...
        {'simulink/Signal Routing/Bus Creator', ...
         'simulink/Commonly Used Blocks/Bus Creator'}, {});
    cat(end+1) = e('busselector', 'BusSelector', 'Bus Selector', 'Aiguillage', ...
        'Reprend des éléments d''un bus par leur nom', ...
        {'OutputSignals', 'signal1,signal2', T; 'OutputAsBus', 'off', {'off', 'on'}}, {}, ...
        {'simulink/Signal Routing/Bus Selector', ...
         'simulink/Commonly Used Blocks/Bus Selector'}, {});
    cat(end+1) = e('mux', 'Mux', 'Mux', 'Aiguillage', ...
        'Réunit ses entrées en un vecteur', ...
        {'Inputs', 2, N}, {}, ...
        {'simulink/Signal Routing/Mux', 'simulink/Commonly Used Blocks/Mux'}, {});
    cat(end+1) = e('demux', 'Demux', 'Demux', 'Aiguillage', ...
        'Sépare un vecteur en ses parties', ...
        {'Outputs', 2, N}, {}, ...
        {'simulink/Signal Routing/Demux', 'simulink/Commonly Used Blocks/Demux'}, {});
    cat(end+1) = e('selector', 'Selector', 'Selector', 'Aiguillage', ...
        'Choisit des éléments de son entrée par leurs indices', ...
        {'Indices', 1, N; 'InputPortWidth', -1, N}, {}, ...
        {'simulink/Signal Routing/Selector'}, {});
    cat(end+1) = e('concatenate', 'Concatenate', 'Vector Concatenate', 'Aiguillage', ...
        'Met ses entrées bout à bout', ...
        {'NumInputs', 2, N; 'Mode', 'Vector', {'Vector', 'Multidimensional array'}; ...
         'ConcatenateDimension', 1, N}, {}, ...
        {'simulink/Math Operations/Vector Concatenate', ...
         'simulink/Math Operations/Matrix Concatenate', ...
         'simulink/Signal Routing/Vector Concatenate'}, ...
        {'vectorconcatenate', 'matrixconcatenate'});
    cat(end+1) = e('reshape', 'Reshape', 'Reshape', 'Aiguillage', ...
        'Change les dimensions de son entrée', ...
        {'OutputDimensionality', '1-D array', ...
         {'1-D array', 'Column vector (2-D)', 'Row vector (2-D)', 'Customize'}; ...
         'OutputDimensions', [1 1], N}, {}, ...
        {'simulink/Math Operations/Reshape'}, {});
    cat(end+1) = e('goto', 'Goto', 'Goto', 'Aiguillage', ...
        'Envoie son entrée aux blocs From de même étiquette', ...
        {'GotoTag', 'A', T; 'TagVisibility', 'local', {'local', 'scoped', 'global'}}, ...
        {}, {'simulink/Signal Routing/Goto'}, {});
    cat(end+1) = e('from', 'From', 'From', 'Aiguillage', ...
        'Rend le signal du bloc Goto de même étiquette', ...
        {'GotoTag', 'A', T}, {}, {'simulink/Signal Routing/From'}, {});
    % NombreDePorts n'est pas un réglage de Simulink : c'est le dépliage
    % d'un sous-système à plusieurs sorties qui le pose, le bloc laissant
    % alors passer chaque entrée vers la sortie de même rang.
    cat(end+1) = e('signalconversion', 'SignalConversion', 'Signal Conversion', ...
        'Aiguillage', 'Laisse passer son entrée', ...
        {'ConversionOutput', 'Signal copy', {'Signal copy', 'Virtual bus', ...
         'Nonvirtual bus'}; 'NombreDePorts', 1, N}, {}, ...
        {'simulink/Signal Attributes/Signal Conversion'}, {});

    % --- Continu ---
    cat(end+1) = e('integrator', 'Integrator', 'Integrator', 'Continu', ...
        'Intègre : 1/s, bornes éventuelles', ...
        {'InitialCondition', 0, N; 'LimitOutput', 'off', {'on', 'off'}; ...
         'UpperSaturationLimit', Inf, N; 'LowerSaturationLimit', -Inf, N; 'ZeroCross', 'on', {'on', 'off'}}, ...
        {'X0', 'InitialCondition'}, ...
        {'simulink/Continuous/Integrator', 'simulink/Commonly Used Blocks/Integrator'}, ...
        {});
    cat(end+1) = e('derivative', 'Derivative', 'Derivative', 'Continu', ...
        'Dérive : du/dt', {}, {}, {'simulink/Continuous/Derivative'}, {});
    cat(end+1) = e('transferfcn', 'TransferFcn', 'Transfer Fcn', 'Continu', ...
        'Une transmittance en s', ...
        {'Numerator', 1, N; 'Denominator', 1, N}, {}, ...
        {'simulink/Continuous/Transfer Fcn'}, {});
    cat(end+1) = e('statespace', 'StateSpace', 'State-Space', 'Continu', ...
        'Une représentation d''état, à plusieurs voies', ...
        {'A', 0, N; 'B', 0, N; 'C', 1, N; 'D', 0, N; 'X0', [], N}, ...
        {'InitialCondition', 'X0'}, {'simulink/Continuous/State-Space'}, {});
    cat(end+1) = e('zeropole', 'ZeroPole', 'Zero-Pole', 'Continu', ...
        'Une transmittance donnée par ses zéros, ses pôles et son gain', ...
        {'Zeros', [], N; 'Poles', -1, N; 'Gain', 1, N}, {}, ...
        {'simulink/Continuous/Zero-Pole'}, {});
    cat(end+1) = e('transportdelay', 'TransportDelay', 'Transport Delay', 'Continu', ...
        'Retarde le signal d''une durée', ...
        {'DelayTime', 1, N; 'InitialOutput', 0, N; 'BufferSize', 1024, N}, {}, ...
        {'simulink/Continuous/Transport Delay'}, {});
    cat(end+1) = e('pidcontroller', 'PIDController', 'PID Controller', 'Continu', ...
        'Un PID parallèle, dérivée filtrée par N/(1+N/s)', ...
        {'P', 1, N; 'I', 0, N; 'D', 0, N; 'N', 100, N; ...
         'InitialConditionForIntegrator', 0, N; 'InitialConditionForFilter', 0, N; ...
         'Form', 'Parallel', {'Parallel'}}, {}, ...
        {'simulink/Continuous/PID Controller'}, {'pid'});

    % --- Discret ---
    cat(end+1) = e('delay', 'Delay', 'Delay', 'Discret', ...
        'Retarde de N pas : z^-N', ...
        {'InitialCondition', 0, N; 'DelayLength', 1, N; 'SampleTime', [], N}, ...
        {'X0', 'InitialCondition'}, ...
        {'simulink/Discrete/Delay', 'simulink/Discrete/Unit Delay', ...
         'simulink/Commonly Used Blocks/Unit Delay'}, {'unitdelay'});
    cat(end+1) = e('memory', 'Memory', 'Memory', 'Discret', ...
        'La valeur de l''entrée au pas précédent', ...
        {'InitialCondition', 0, N}, {'X0', 'InitialCondition'}, ...
        {'simulink/Discrete/Memory'}, {});
    cat(end+1) = e('zoh', 'ZeroOrderHold', 'Zero-Order Hold', 'Discret', ...
        'Tenue d''ordre zéro ; période par défaut : dix pas', ...
        {'SampleTime', [], N}, {}, {'simulink/Discrete/Zero-Order Hold'}, ...
        {'zeroorderhold'});
    cat(end+1) = e('discreteintegrator', 'DiscreteIntegrator', ...
        'Discrete-Time Integrator', 'Discret', 'Intègre à période fixe', ...
        {'Gain', 1, N; 'SampleTime', [], N; 'IntegratorMethod', 'ForwardEuler', ...
         {'ForwardEuler', 'BackwardEuler', 'Trapezoidal'}; 'InitialCondition', 0, N}, ...
        {'gainval', 'Gain'}, {'simulink/Discrete/Discrete-Time Integrator'}, ...
        {'discrete-timeintegrator'});
    cat(end+1) = e('discretetransferfcn', 'DiscreteTransferFcn', ...
        'Discrete Transfer Fcn', 'Discret', 'Une transmittance en z', ...
        {'Numerator', 1, N; 'Denominator', 1, N; 'SampleTime', [], N}, {}, ...
        {'simulink/Discrete/Discrete Transfer Fcn'}, {});
    cat(end+1) = e('discretefilter', 'DiscreteFilter', 'Discrete Filter', 'Discret', ...
        'Un filtre en puissances croissantes de z^-1', ...
        {'Numerator', 1, N; 'Denominator', [1 0.5], N; 'SampleTime', [], N}, {}, ...
        {'simulink/Discrete/Discrete Filter'}, {});
    cat(end+1) = e('discretestatespace', 'DiscreteStateSpace', ...
        'Discrete State-Space', 'Discret', ...
        'Une représentation d''état échantillonnée, à plusieurs voies', ...
        {'A', 0, N; 'B', 0, N; 'C', 1, N; 'D', 0, N; 'X0', [], N; 'SampleTime', [], N}, ...
        {'InitialCondition', 'X0'}, {'simulink/Discrete/Discrete State-Space'}, {});

    % --- Sorties ---
    cat(end+1) = e('outport', 'Outport', 'Out1', 'Sorties', ...
        'La sortie du modèle, vue par LINMOD', ...
        {'Port', 1, N; 'InitialOutput', 0, N; ...
         'OutputWhenDisabled', 'held', {'held', 'reset'}}, {}, ...
        {'simulink/Sinks/Out1', 'simulink/Ports & Subsystems/Out1', ...
         'simulink/Commonly Used Blocks/Out1'}, {'out1', 'out'});
    cat(end+1) = e('scope', 'Scope', 'Scope', 'Sorties', ...
        'Un oscilloscope : chaque entrée est relevée', ...
        {'NumInputPorts', 1, N}, {}, ...
        {'simulink/Sinks/Scope', 'simulink/Commonly Used Blocks/Scope'}, {});
    cat(end+1) = e('display', 'Display', 'Display', 'Sorties', ...
        'Affiche la valeur de son entrée', ...
        {'Format', 'short', {'short', 'long', 'short_e', 'long_e', 'bank', 'hex'}}, {}, ...
        {'simulink/Sinks/Display'}, {});
    cat(end+1) = e('toworkspace', 'ToWorkspace', 'To Workspace', 'Sorties', ...
        'Dépose le signal dans l''espace de travail', ...
        {'VariableName', 'simout', T; 'SaveFormat', 'Array', ...
         {'Array', 'Structure With Time', 'Structure'}}, {}, ...
        {'simulink/Sinks/To Workspace'}, {});
    cat(end+1) = e('terminator', 'Terminator', 'Terminator', 'Sorties', ...
        'Ferme une sortie qu''on ne lit pas', {}, {}, ...
        {'simulink/Sinks/Terminator', 'simulink/Commonly Used Blocks/Terminator'}, {});
    cat(end+1) = e('stopsimulation', 'Stop', 'Stop Simulation', 'Sorties', ...
        'Arrête la simulation dès que son entrée n''est plus nulle', {}, {}, ...
        {'simulink/Sinks/Stop Simulation'}, {'stop'});
    cat(end+1) = e('assertion', 'Assertion', 'Assertion', 'Sorties', ...
        'Échoue dès que son entrée s''annule', ...
        {'Enabled', 'on', {'on', 'off'}; 'StopWhenAssertionFail', 'on', {'on', 'off'}}, ...
        {}, {'simulink/Model Verification/Assertion'}, {});

    % --- Fonctions de l'utilisateur ---
    cat(end+1) = e('fcn', 'Fcn', 'Fcn', 'Fonctions', ...
        'Une expression de l''entrée u, écrite comme en MATLAB : u(1)*sin(u(2))', ...
        {'Expr', 'sin(u(1)*exp(2.3*(-u(2))))', T; 'SampleTime', -1, N}, {}, ...
        {'simulink/User-Defined Functions/Fcn'}, {});
    cat(end+1) = e('matlabfunction', 'MATLABFunction', 'MATLAB Function', 'Fonctions', ...
        'Une fonction MATLAB : ses arguments sont les entrées, ses sorties les sorties', ...
        {'Script', sprintf('function y = fcn(u)\ny = u;'), T; 'SampleTime', -1, N}, {}, ...
        {'simulink/User-Defined Functions/MATLAB Function'}, {'emlblock'});
    cat(end+1) = e('interpretedmatlabfunction', 'MATLABFcn', ...
        'Interpreted MATLAB Function', 'Fonctions', ...
        'Une fonction MATLAB appliquée à l''entrée : un nom, ou une expression de u', ...
        {'MATLABFcn', 'sin', T; 'OutputDimensions', -1, N; 'SampleTime', -1, N}, {}, ...
        {'simulink/User-Defined Functions/Interpreted MATLAB Function'}, ...
        {'matlabfcn'});
    cat(end+1) = e('sfunction', 'S-Function', 'S-Function', 'Fonctions', ...
        'Une S-fonction de niveau 1 écrite en MATLAB : [sys,x0,str,ts] = f(t,x,u,flag)', ...
        {'FunctionName', 'system', T; 'Parameters', '', T}, {}, ...
        {'simulink/User-Defined Functions/S-Function'}, {'sfun'});

    % --- Stateflow ---
    cat(end+1) = e('chart', 'Chart', 'Chart', 'Stateflow', ...
        'Une machine à états de Stateflow (SFCHART), qui fait un pas à chaque instant', ...
        {'Chart', [], 'libre'; 'Inputs', 1, N; 'Outputs', {'etat'}, 'libre'; ...
         'InitialContext', struct(), 'libre'; 'SampleTime', -1, N}, {}, ...
        {'sflib/Chart', 'simulink/Stateflow/Chart'}, {'stateflow'});

    % --- Sous-systèmes ---
    cat(end+1) = e('subsystem', 'SubSystem', 'Subsystem', 'Sous-systèmes', ...
        'Un schéma entier abrégé en un bloc', ...
        {'Model', [], 'modele'; 'Mask', 'off', {'off', 'on'}; 'MaskVariables', '', T; ...
         'MaskValueString', '', T; 'MaskPrompts', {}, 'libre'}, {'Modele', 'Model'}, ...
        {'simulink/Ports & Subsystems/Subsystem', ...
         'simulink/Commonly Used Blocks/Subsystem', ...
         'simulink/Ports & Subsystems/Enabled Subsystem', ...
         'simulink/Ports & Subsystems/Triggered Subsystem', ...
         'simulink/Ports & Subsystems/Enabled and Triggered Subsystem', ...
         'simulink/Ports & Subsystems/If Action Subsystem', ...
         'simulink/Ports & Subsystems/Switch Case Action Subsystem'}, ...
        {'enabledsubsystem', 'triggeredsubsystem', 'enabledandtriggeredsubsystem', ...
         'ifactionsubsystem', 'switchcaseactionsubsystem'});
    % Les ports de contrôle se posent dans un sous-système : ils en font un
    % sous-système conditionnel, qui ne calcule que quand son entrée de
    % contrôle le permet, et tient ses sorties le reste du temps.
    cat(end+1) = e('enableport', 'EnablePort', 'Enable', 'Sous-systèmes', ...
        'Dans un sous-système : il ne calcule que quand ce port reçoit un signal positif', ...
        {'StatesWhenEnabling', 'held', {'held', 'reset'}; ...
         'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Ports & Subsystems/Enable'}, {'enable'});
    cat(end+1) = e('triggerport', 'TriggerPort', 'Trigger', 'Sous-systèmes', ...
        'Dans un sous-système : il ne calcule qu''au front du signal de ce port', ...
        {'TriggerType', 'rising', {'rising', 'falling', 'either'}; ...
         'ZeroCross', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Ports & Subsystems/Trigger'}, {'trigger'});
    cat(end+1) = e('actionport', 'ActionPort', 'Action Port', 'Sous-systèmes', ...
        'Dans un sous-système : il calcule quand un bloc If ou Switch Case le désigne', ...
        {'InitializeStates', 'held', {'held', 'reset'}}, {}, ...
        {'simulink/Ports & Subsystems/Action Port'}, {'action'});
    cat(end+1) = e('if', 'If', 'If', 'Sous-systèmes', ...
        'Choisit, par des conditions sur ses entrées u1, u2..., le sous-système d''action qui calcule', ...
        {'NumInputs', 1, N; 'IfExpression', 'u1 > 0', T; 'ElseIfExpressions', '', T; ...
         'ShowElse', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Ports & Subsystems/If'}, {});
    cat(end+1) = e('switchcase', 'SwitchCase', 'Switch Case', 'Sous-systèmes', ...
        'Choisit, selon la valeur entière de son entrée, le sous-système d''action qui calcule', ...
        {'CaseConditions', '{1}', T; 'ShowDefaultCase', 'on', {'on', 'off'}}, {}, ...
        {'simulink/Ports & Subsystems/Switch Case'}, {});
    cat(end+1) = e('merge', 'Merge', 'Merge', 'Aiguillage', ...
        'Rend celle de ses entrées dont le sous-système vient de calculer', ...
        {'Inputs', 2, N; 'InitialOutput', 0, N}, {}, ...
        {'simulink/Signal Routing/Merge'}, {});
    % La garde : ce que devient le port de contrôle d'un sous-système
    % déplié. Elle n'est pas dans la bibliothèque.
    cat(end+1) = e('garde', 'MatLibreGarde', 'Garde', 'Interne', ...
        'Interne : la condition d''un sous-système conditionnel déplié', ...
        {'Enable', 0, N; 'Trigger', 'none', {'none', 'rising', 'falling', 'either'}; ...
         'Action', 0, N; 'Reset', 0, N; 'ZeroCross', 'on', {'on', 'off'}}, {}, {}, {});
end

function x = e(type, simulink, affiche, famille, description, params, alias, ...
               chemins, aliasTypes)
    x = struct('type', type, 'simulink', simulink, 'affiche', affiche, ...
               'famille', famille, 'description', description, ...
               'params', {params}, 'alias', {alias}, 'chemins', {chemins}, ...
               'aliasTypes', {aliasTypes});
end

% Les réglages que tout bloc accepte : ils disent où il est et comment il
% se montre, rien de ce qu'il calcule.
function noms = parametresCommuns()
    noms = {'Position', 'Orientation', 'ForegroundColor', 'BackgroundColor', ...
            'ShowName', 'Description', 'Tag', 'Priority', 'NamePlacement', ...
            'FontSize', 'FontName', 'DropShadow', 'AttributesFormatString', ...
            'UserData'};
end

% --- les recherches ---------------------------------------------------------

function index = indexer(cat)
    index = containers.Map();
    for k = 1:numel(cat)
        cles = [{cat(k).type, cat(k).simulink, cat(k).affiche}, cat(k).chemins, ...
                cat(k).aliasTypes];
        for j = 1:numel(cles)
            cle = normaliser(cles{j});
            if ~isKey(index, cle)
                index(cle) = k;
            end
        end
    end
end

% Une désignation se compare sans la casse ni les espaces : « Sine Wave »,
% « sinewave » et « SineWave » désignent le même bloc.
function cle = normaliser(texte)
    cle = lower(regexprep(char(texte), '\s', ''));
end

function x = resoudreType(cat, index, designation)
    if isstruct(designation)
        x = designation;
        return
    end
    brut = char(designation);
    cle = normaliser(brut);
    if isKey(index, cle)
        x = cat(index(cle));
        return
    end
    % Un chemin de bibliothèque qu'on ne connaît pas en entier : son
    % dernier segment est le nom du bloc.
    barre = find(brut == '/', 1, 'last');
    if ~isempty(barre)
        dernier = normaliser(brut(barre + 1:end));
        if isKey(index, dernier)
            x = cat(index(dernier));
            return
        end
    end
    error('Simulink:Commands:InvalidBlockType', ...
          ['Le type de bloc ''%s'' est inconnu. Les types reconnus sont ceux ' ...
           'qu''ADD_BLOCK decrit ; ils se designent aussi par leur nom Simulink ' ...
           '(''Gain'', ''Sine Wave'') ou leur chemin de bibliotheque ' ...
           '(''simulink/Math Operations/Gain'').'], brut);
end

function nom = resoudreParametre(x, demande)
    nom = '';
    demande = char(demande);
    for k = 1:size(x.params, 1)
        if strcmpi(x.params{k, 1}, demande)
            nom = x.params{k, 1};
            return
        end
    end
    for k = 1:size(x.alias, 1)
        if strcmpi(x.alias{k, 1}, demande)
            nom = x.alias{k, 2};
            return
        end
    end
    communs = parametresCommuns();
    for k = 1:numel(communs)
        if strcmpi(communs{k}, demande)
            nom = communs{k};
            return
        end
    end
end
