function options = weboptions(varargin)
%WEBOPTIONS Réglages d'une requête web.
%   O = WEBOPTIONS() rend les réglages par défaut. O = WEBOPTIONS(NOM,
%   VALEUR,...) en fixe. L'objet se passe ensuite à WEBREAD, WEBWRITE ou
%   WEBSAVE.
%
%   Les réglages reconnus : 'Timeout' (secondes), 'ContentType'
%   ('auto', 'text', 'json', 'raw'), 'MediaType' (le type envoyé),
%   'RequestMethod' ('auto', 'get', 'post', 'put', 'delete'),
%   'CharacterEncoding', 'UserAgent', 'Username', 'Password',
%   'HeaderFields' (une matrice de cellules à deux colonnes) et
%   'CertificateFilename'.
%
%   Exemple :
%      o = weboptions('Timeout', 30, 'ContentType', 'json');
%      o.Timeout                       % 30
%      o.ContentType                   % 'json'
%
%   Voir aussi WEBREAD, WEBWRITE, WEBSAVE, URLREAD.
    defauts = struct('CharacterEncoding', 'auto', ...
                     'UserAgent', 'MatLibre', ...
                     'Timeout', 5, ...
                     'Username', '', ...
                     'Password', '', ...
                     'KeyName', '', ...
                     'KeyValue', '', ...
                     'HeaderFields', {{}}, ...
                     'ContentType', 'auto', ...
                     'ContentReader', [], ...
                     'MediaType', 'auto', ...
                     'RequestMethod', 'auto', ...
                     'ArrayFormat', 'csv', ...
                     'CertificateFilename', '');
    options = matlibre_lire_options(varargin, defauts);
end
