function couche = tanhLayer(varargin)
%TANHLAYER Couche à tangente hyperbolique.
    couche = struct('type', 'tanh', 'sorties', 0, 'W', [], 'b', [], ...
                    'entree', [], 'sortie', [], ...
                    'nom', matlibre_couche_nom(varargin));
end
