function options = bodeoptions(gabarit)
%BODEOPTIONS Options d'un diagramme de Bode.
%   O = BODEOPTIONS rend une structure d'options de tracé, que BODE
%   accepte comme dernier argument : unités, grille, plages, titres.
%   O = BODEOPTIONS('cstprefs') part des préférences enregistrées ;
%   MatLibre n'en garde pas, et rend les mêmes valeurs par défaut.
%
%   Champs traités par MatLibre : FreqUnits, MagUnits, PhaseUnits, Grid,
%   XLim, YLim, Title, XLabel, YLabel. Les autres sont acceptés et
%   conservés, pour que le code écrit pour MATLAB s'exécute.
%
%   Exemple :
%      o = bodeoptions;
%      o.FreqUnits = 'Hz';
%      o.Grid = 'on';
%      bode(tf(1, [1 1]), o);
%
%   Voir aussi BODE, BODEMAG, NICHOLS, NYQUIST, STEPDATAOPTIONS.
    if nargin > 0 && ~isempty(gabarit) && ~strcmpi(char(gabarit), 'cstprefs')
        error('control:bodeoptions:Gabarit', ...
              'Seul le gabarit ''cstprefs'' est reconnu.');
    end
    options = struct('FreqUnits', 'rad/s', 'FreqScale', 'log', ...
                     'MagUnits', 'dB', 'MagScale', 'linear', 'MagVisible', 'on', ...
                     'PhaseUnits', 'deg', 'PhaseVisible', 'on', ...
                     'PhaseWrapping', 'off', 'PhaseMatching', 'off', ...
                     'Grid', 'off', 'XLim', {{}}, 'YLim', {{}}, ...
                     'XLimMode', 'auto', 'YLimMode', 'auto', ...
                     'Title', struct('String', ''), ...
                     'XLabel', struct('String', ''), ...
                     'YLabel', struct('String', ''), ...
                     'IOGrouping', 'none', 'InputLabels', struct('FontSize', 8), ...
                     'OutputLabels', struct('FontSize', 8));
end
